package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AalexCrocessId generated by hbm2java
 */
@Embeddable
public class AalexCrocessId implements java.io.Serializable {

	private String oederNo;
	private String cono;
	private String conoStatus;
	private String iaStatus;

	public AalexCrocessId() {
	}

	public AalexCrocessId(String oederNo, String cono, String conoStatus, String iaStatus) {
		this.oederNo = oederNo;
		this.cono = cono;
		this.conoStatus = conoStatus;
		this.iaStatus = iaStatus;
	}

	@Column(name = "OEDER_NO", length = 20)
	public String getOederNo() {
		return this.oederNo;
	}

	public void setOederNo(String oederNo) {
		this.oederNo = oederNo;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "CONO_STATUS", length = 20)
	public String getConoStatus() {
		return this.conoStatus;
	}

	public void setConoStatus(String conoStatus) {
		this.conoStatus = conoStatus;
	}

	@Column(name = "IA_STATUS", length = 20)
	public String getIaStatus() {
		return this.iaStatus;
	}

	public void setIaStatus(String iaStatus) {
		this.iaStatus = iaStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AalexCrocessId))
			return false;
		AalexCrocessId castOther = (AalexCrocessId) other;

		return ((this.getOederNo() == castOther.getOederNo()) || (this.getOederNo() != null
				&& castOther.getOederNo() != null && this.getOederNo().equals(castOther.getOederNo())))
				&& ((this.getCono() == castOther.getCono()) || (this.getCono() != null && castOther.getCono() != null
						&& this.getCono().equals(castOther.getCono())))
				&& ((this.getConoStatus() == castOther.getConoStatus()) || (this.getConoStatus() != null
						&& castOther.getConoStatus() != null && this.getConoStatus().equals(castOther.getConoStatus())))
				&& ((this.getIaStatus() == castOther.getIaStatus()) || (this.getIaStatus() != null
						&& castOther.getIaStatus() != null && this.getIaStatus().equals(castOther.getIaStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOederNo() == null ? 0 : this.getOederNo().hashCode());
		result = 37 * result + (getCono() == null ? 0 : this.getCono().hashCode());
		result = 37 * result + (getConoStatus() == null ? 0 : this.getConoStatus().hashCode());
		result = 37 * result + (getIaStatus() == null ? 0 : this.getIaStatus().hashCode());
		return result;
	}

}
