package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AalexCrocess generated by hbm2java
 */
@Entity
@Table(name = "AALEX_CROCESS")
public class AalexCrocess implements java.io.Serializable {

	private AalexCrocessId id;

	public AalexCrocess() {
	}

	public AalexCrocess(AalexCrocessId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "oederNo", column = @Column(name = "OEDER_NO", length = 20)),
			@AttributeOverride(name = "cono", column = @Column(name = "CONO", length = 20)),
			@AttributeOverride(name = "conoStatus", column = @Column(name = "CONO_STATUS", length = 20)),
			@AttributeOverride(name = "iaStatus", column = @Column(name = "IA_STATUS", length = 20)) })
	public AalexCrocessId getId() {
		return this.id;
	}

	public void setId(AalexCrocessId id) {
		this.id = id;
	}

}
