package com.fet.db.oracle.pojo;
// Generated 2020/11/9 �W�� 10:18:20 by Hibernate Tools 5.3.18.Final

import java.util.Date;

/**
 * Acc2giftLog generated by hbm2java
 */
public class Acc2giftLog implements java.io.Serializable {

	private String seq;
	private String fetNo;
	private Character toGift;
	private Integer quantity;
	private Date transDate;

	public Acc2giftLog() {
	}

	public Acc2giftLog(String seq) {
		this.seq = seq;
	}

	public Acc2giftLog(String seq, String fetNo, Character toGift, Integer quantity, Date transDate) {
		this.seq = seq;
		this.fetNo = fetNo;
		this.toGift = toGift;
		this.quantity = quantity;
		this.transDate = transDate;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getFetNo() {
		return this.fetNo;
	}

	public void setFetNo(String fetNo) {
		this.fetNo = fetNo;
	}

	public Character getToGift() {
		return this.toGift;
	}

	public void setToGift(Character toGift) {
		this.toGift = toGift;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

}
