package com.fet.db.oracle.pojo;
// Generated 2020/11/10 �U�� 01:25:20 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acc2giftLog generated by hbm2java
 */
@Entity
@Table(name = "ACC2GIFT_LOG", schema = "ES_DEV")
public class Acc2giftLog implements java.io.Serializable {

	private String seq;
	private String fetNo;
	private Character toGift;
	private Integer quantity;
	private Date transDate;

	public Acc2giftLog() {
	}

	public Acc2giftLog(String seq) {
		this.seq = seq;
	}

	public Acc2giftLog(String seq, String fetNo, Character toGift, Integer quantity, Date transDate) {
		this.seq = seq;
		this.fetNo = fetNo;
		this.toGift = toGift;
		this.quantity = quantity;
		this.transDate = transDate;
	}

	@Id

	@Column(name = "SEQ", unique = true, nullable = false, length = 32)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "FET_NO", length = 32)
	public String getFetNo() {
		return this.fetNo;
	}

	public void setFetNo(String fetNo) {
		this.fetNo = fetNo;
	}

	@Column(name = "TO_GIFT", length = 1)
	public Character getToGift() {
		return this.toGift;
	}

	public void setToGift(Character toGift) {
		this.toGift = toGift;
	}

	@Column(name = "QUANTITY", precision = 8, scale = 0)
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRANS_DATE", length = 7)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

}
