// default package
// Generated 2020/11/6 �U�� 06:23:13 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CrossCooperationId generated by hbm2java
 */
@Embeddable
public class CrossCooperationId implements java.io.Serializable {

	private String orderNo;
	private String userName;
	private String userMobile;
	private String orderType;
	private String msisdn;
	private String pcode;
	private String onsaleName;
	private String productName;
	private String fetno;
	private long productPrice;
	private long prepayment;
	private long totalAmount;
	private String cancelFlag;
	private String smsUrl;
	private String cono;
	private Date createDate;
	private String createTimestamp;
	private Date updateDate;
	private String SOrderNo;
	private String orderStatus;

	public CrossCooperationId() {
	}

	public CrossCooperationId(String orderNo, long productPrice, long prepayment, long totalAmount) {
		this.orderNo = orderNo;
		this.productPrice = productPrice;
		this.prepayment = prepayment;
		this.totalAmount = totalAmount;
	}

	public CrossCooperationId(String orderNo, String userName, String userMobile, String orderType, String msisdn,
			String pcode, String onsaleName, String productName, String fetno, long productPrice, long prepayment,
			long totalAmount, String cancelFlag, String smsUrl, String cono, Date createDate, String createTimestamp,
			Date updateDate, String SOrderNo, String orderStatus) {
		this.orderNo = orderNo;
		this.userName = userName;
		this.userMobile = userMobile;
		this.orderType = orderType;
		this.msisdn = msisdn;
		this.pcode = pcode;
		this.onsaleName = onsaleName;
		this.productName = productName;
		this.fetno = fetno;
		this.productPrice = productPrice;
		this.prepayment = prepayment;
		this.totalAmount = totalAmount;
		this.cancelFlag = cancelFlag;
		this.smsUrl = smsUrl;
		this.cono = cono;
		this.createDate = createDate;
		this.createTimestamp = createTimestamp;
		this.updateDate = updateDate;
		this.SOrderNo = SOrderNo;
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_NO", nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_MOBILE", length = 10)
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "ORDER_TYPE", length = 2)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "PCODE", length = 50)
	public String getPcode() {
		return this.pcode;
	}

	public void setPcode(String pcode) {
		this.pcode = pcode;
	}

	@Column(name = "ONSALE_NAME", length = 100)
	public String getOnsaleName() {
		return this.onsaleName;
	}

	public void setOnsaleName(String onsaleName) {
		this.onsaleName = onsaleName;
	}

	@Column(name = "PRODUCT_NAME", length = 200)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "FETNO", length = 32)
	public String getFetno() {
		return this.fetno;
	}

	public void setFetno(String fetno) {
		this.fetno = fetno;
	}

	@Column(name = "PRODUCT_PRICE", nullable = false, precision = 11, scale = 0)
	public long getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(long productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "PREPAYMENT", nullable = false, precision = 11, scale = 0)
	public long getPrepayment() {
		return this.prepayment;
	}

	public void setPrepayment(long prepayment) {
		this.prepayment = prepayment;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 11, scale = 0)
	public long getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(long totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "CANCEL_FLAG", length = 1)
	public String getCancelFlag() {
		return this.cancelFlag;
	}

	public void setCancelFlag(String cancelFlag) {
		this.cancelFlag = cancelFlag;
	}

	@Column(name = "SMS_URL", length = 200)
	public String getSmsUrl() {
		return this.smsUrl;
	}

	public void setSmsUrl(String smsUrl) {
		this.smsUrl = smsUrl;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_TIMESTAMP", length = 20)
	public String getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(String createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "S_ORDER_NO", length = 200)
	public String getSOrderNo() {
		return this.SOrderNo;
	}

	public void setSOrderNo(String SOrderNo) {
		this.SOrderNo = SOrderNo;
	}

	@Column(name = "ORDER_STATUS", length = 10)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrossCooperationId))
			return false;
		CrossCooperationId castOther = (CrossCooperationId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null
				&& castOther.getOrderNo() != null && this.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserMobile() == castOther.getUserMobile()) || (this.getUserMobile() != null
						&& castOther.getUserMobile() != null && this.getUserMobile().equals(castOther.getUserMobile())))
				&& ((this.getOrderType() == castOther.getOrderType()) || (this.getOrderType() != null
						&& castOther.getOrderType() != null && this.getOrderType().equals(castOther.getOrderType())))
				&& ((this.getMsisdn() == castOther.getMsisdn()) || (this.getMsisdn() != null
						&& castOther.getMsisdn() != null && this.getMsisdn().equals(castOther.getMsisdn())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null
						&& castOther.getPcode() != null && this.getPcode().equals(castOther.getPcode())))
				&& ((this.getOnsaleName() == castOther.getOnsaleName()) || (this.getOnsaleName() != null
						&& castOther.getOnsaleName() != null && this.getOnsaleName().equals(castOther.getOnsaleName())))
				&& ((this.getProductName() == castOther.getProductName())
						|| (this.getProductName() != null && castOther.getProductName() != null
								&& this.getProductName().equals(castOther.getProductName())))
				&& ((this.getFetno() == castOther.getFetno()) || (this.getFetno() != null
						&& castOther.getFetno() != null && this.getFetno().equals(castOther.getFetno())))
				&& (this.getProductPrice() == castOther.getProductPrice())
				&& (this.getPrepayment() == castOther.getPrepayment())
				&& (this.getTotalAmount() == castOther.getTotalAmount())
				&& ((this.getCancelFlag() == castOther.getCancelFlag()) || (this.getCancelFlag() != null
						&& castOther.getCancelFlag() != null && this.getCancelFlag().equals(castOther.getCancelFlag())))
				&& ((this.getSmsUrl() == castOther.getSmsUrl()) || (this.getSmsUrl() != null
						&& castOther.getSmsUrl() != null && this.getSmsUrl().equals(castOther.getSmsUrl())))
				&& ((this.getCono() == castOther.getCono()) || (this.getCono() != null && castOther.getCono() != null
						&& this.getCono().equals(castOther.getCono())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateTimestamp() == castOther.getCreateTimestamp())
						|| (this.getCreateTimestamp() != null && castOther.getCreateTimestamp() != null
								&& this.getCreateTimestamp().equals(castOther.getCreateTimestamp())))
				&& ((this.getUpdateDate() == castOther.getUpdateDate()) || (this.getUpdateDate() != null
						&& castOther.getUpdateDate() != null && this.getUpdateDate().equals(castOther.getUpdateDate())))
				&& ((this.getSOrderNo() == castOther.getSOrderNo()) || (this.getSOrderNo() != null
						&& castOther.getSOrderNo() != null && this.getSOrderNo().equals(castOther.getSOrderNo())))
				&& ((this.getOrderStatus() == castOther.getOrderStatus())
						|| (this.getOrderStatus() != null && castOther.getOrderStatus() != null
								&& this.getOrderStatus().equals(castOther.getOrderStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getUserMobile() == null ? 0 : this.getUserMobile().hashCode());
		result = 37 * result + (getOrderType() == null ? 0 : this.getOrderType().hashCode());
		result = 37 * result + (getMsisdn() == null ? 0 : this.getMsisdn().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getOnsaleName() == null ? 0 : this.getOnsaleName().hashCode());
		result = 37 * result + (getProductName() == null ? 0 : this.getProductName().hashCode());
		result = 37 * result + (getFetno() == null ? 0 : this.getFetno().hashCode());
		result = 37 * result + (int) this.getProductPrice();
		result = 37 * result + (int) this.getPrepayment();
		result = 37 * result + (int) this.getTotalAmount();
		result = 37 * result + (getCancelFlag() == null ? 0 : this.getCancelFlag().hashCode());
		result = 37 * result + (getSmsUrl() == null ? 0 : this.getSmsUrl().hashCode());
		result = 37 * result + (getCono() == null ? 0 : this.getCono().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getCreateTimestamp() == null ? 0 : this.getCreateTimestamp().hashCode());
		result = 37 * result + (getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode());
		result = 37 * result + (getSOrderNo() == null ? 0 : this.getSOrderNo().hashCode());
		result = 37 * result + (getOrderStatus() == null ? 0 : this.getOrderStatus().hashCode());
		return result;
	}

}
