// default package
// Generated 2020/11/6 �U�� 06:23:13 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CrossCooperationMapping generated by hbm2java
 */
@Entity
@Table(name = "CROSS_COOPERATION_MAPPING", schema = "ES_DEV")
public class CrossCooperationMapping implements java.io.Serializable {

	private CrossCooperationMappingId id;

	public CrossCooperationMapping() {
	}

	public CrossCooperationMapping(CrossCooperationMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemId", column = @Column(name = "ITEM_ID", length = 20)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "MODULE_ID", length = 20)),
			@AttributeOverride(name = "pcode", column = @Column(name = "PCODE", length = 50)),
			@AttributeOverride(name = "onsaleName", column = @Column(name = "ONSALE_NAME", length = 100)),
			@AttributeOverride(name = "productName", column = @Column(name = "PRODUCT_NAME", length = 200)),
			@AttributeOverride(name = "fetno", column = @Column(name = "FETNO", length = 32)),
			@AttributeOverride(name = "productPrice", column = @Column(name = "PRODUCT_PRICE", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "prepayment", column = @Column(name = "PREPAYMENT", nullable = false, precision = 11, scale = 0)) })
	public CrossCooperationMappingId getId() {
		return this.id;
	}

	public void setId(CrossCooperationMappingId id) {
		this.id = id;
	}

}
