// default package
// Generated 2020/11/6 �U�� 06:23:13 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CrossCooperation generated by hbm2java
 */
@Entity
@Table(name = "CROSS_COOPERATION", schema = "ES_DEV")
public class CrossCooperation implements java.io.Serializable {

	private CrossCooperationId id;

	public CrossCooperation() {
	}

	public CrossCooperation(CrossCooperationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderNo", column = @Column(name = "ORDER_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "userName", column = @Column(name = "USER_NAME", length = 20)),
			@AttributeOverride(name = "userMobile", column = @Column(name = "USER_MOBILE", length = 10)),
			@AttributeOverride(name = "orderType", column = @Column(name = "ORDER_TYPE", length = 2)),
			@AttributeOverride(name = "msisdn", column = @Column(name = "MSISDN", length = 10)),
			@AttributeOverride(name = "pcode", column = @Column(name = "PCODE", length = 50)),
			@AttributeOverride(name = "onsaleName", column = @Column(name = "ONSALE_NAME", length = 100)),
			@AttributeOverride(name = "productName", column = @Column(name = "PRODUCT_NAME", length = 200)),
			@AttributeOverride(name = "fetno", column = @Column(name = "FETNO", length = 32)),
			@AttributeOverride(name = "productPrice", column = @Column(name = "PRODUCT_PRICE", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "prepayment", column = @Column(name = "PREPAYMENT", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "totalAmount", column = @Column(name = "TOTAL_AMOUNT", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "cancelFlag", column = @Column(name = "CANCEL_FLAG", length = 1)),
			@AttributeOverride(name = "smsUrl", column = @Column(name = "SMS_URL", length = 200)),
			@AttributeOverride(name = "cono", column = @Column(name = "CONO", length = 20)),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7)),
			@AttributeOverride(name = "createTimestamp", column = @Column(name = "CREATE_TIMESTAMP", length = 20)),
			@AttributeOverride(name = "updateDate", column = @Column(name = "UPDATE_DATE", length = 7)),
			@AttributeOverride(name = "SOrderNo", column = @Column(name = "S_ORDER_NO", length = 200)),
			@AttributeOverride(name = "orderStatus", column = @Column(name = "ORDER_STATUS", length = 10)) })
	public CrossCooperationId getId() {
		return this.id;
	}

	public void setId(CrossCooperationId id) {
		this.id = id;
	}

}
