package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FridayOrder generated by hbm2java
 */
@Entity
@Table(name = "FRIDAY_ORDER")
public class FridayOrder implements java.io.Serializable {

	private String id;
	private String fridayUid;
	private String fridayOrderNumber;
	private String pid;
	private String productName;
	private String cono;
	private Date createTime;
	private String chineseName;
	private String email;
	private String msisdn;
	private String city;
	private String area;
	private String address;
	private Date modifyTime;
	private String memo;
	private String orderStatus;
	private Integer refundAmount;
	private Integer FDollar;
	private Long activityId;

	public FridayOrder() {
	}

	public FridayOrder(String id) {
		this.id = id;
	}

	public FridayOrder(String id, String fridayUid, String fridayOrderNumber, String pid, String productName,
			String cono, Date createTime, String chineseName, String email, String msisdn, String city, String area,
			String address, Date modifyTime, String memo, String orderStatus, Integer refundAmount, Integer FDollar,
			Long activityId) {
		this.id = id;
		this.fridayUid = fridayUid;
		this.fridayOrderNumber = fridayOrderNumber;
		this.pid = pid;
		this.productName = productName;
		this.cono = cono;
		this.createTime = createTime;
		this.chineseName = chineseName;
		this.email = email;
		this.msisdn = msisdn;
		this.city = city;
		this.area = area;
		this.address = address;
		this.modifyTime = modifyTime;
		this.memo = memo;
		this.orderStatus = orderStatus;
		this.refundAmount = refundAmount;
		this.FDollar = FDollar;
		this.activityId = activityId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "FRIDAY_UID", length = 20)
	public String getFridayUid() {
		return this.fridayUid;
	}

	public void setFridayUid(String fridayUid) {
		this.fridayUid = fridayUid;
	}

	@Column(name = "FRIDAY_ORDER_NUMBER", length = 20)
	public String getFridayOrderNumber() {
		return this.fridayOrderNumber;
	}

	public void setFridayOrderNumber(String fridayOrderNumber) {
		this.fridayOrderNumber = fridayOrderNumber;
	}

	@Column(name = "PID", length = 20)
	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "PRODUCT_NAME", length = 2000)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "CONO", length = 32)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_TIME", length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CHINESE_NAME", length = 40)
	public String getChineseName() {
		return this.chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "AREA", length = 20)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "ADDRESS", length = 600)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", length = 7)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MEMO", length = 20)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "ORDER_STATUS", length = 20)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "REFUND_AMOUNT", precision = 8, scale = 0)
	public Integer getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(Integer refundAmount) {
		this.refundAmount = refundAmount;
	}

	@Column(name = "F_DOLLAR", precision = 6, scale = 0)
	public Integer getFDollar() {
		return this.FDollar;
	}

	public void setFDollar(Integer FDollar) {
		this.FDollar = FDollar;
	}

	@Column(name = "ACTIVITY_ID", precision = 15, scale = 0)
	public Long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

}
