package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MailingList generated by hbm2java
 */
@Entity
@Table(name = "MAILING_LIST")
public class MailingList implements java.io.Serializable {

	private long id;
	private String email;
	private String name;
	private String msisdn;
	private String groupName;

	public MailingList() {
	}

	public MailingList(long id) {
		this.id = id;
	}

	public MailingList(long id, String email, String name, String msisdn, String groupName) {
		this.id = id;
		this.email = email;
		this.name = name;
		this.msisdn = msisdn;
		this.groupName = groupName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "MSISDN", length = 15)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "GROUP_NAME", length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
