package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NbaCoMaster generated by hbm2java
 */
@Entity
@Table(name = "NBA_CO_MASTER")
public class NbaCoMaster implements java.io.Serializable {

	private String cono;
	private String seq;
	private Date coDate;
	private String coType;
	private String salesNo;
	private String userId;
	private String userName;
	private String birthday;
	private Character sex;
	private String rocId;
	private Character secDoc;
	private String secId;
	private Character payType;
	private String virtualAcct;
	private String reccipient;
	private Character deliType;
	private String storeno;
	private Character companycode;
	private String memo;
	private Character deliAlt;
	private Character deliTime;
	private String deliAreacode;
	private String deliAddr;
	private String deliRemark;
	private String billAreacode;
	private String billAddr;
	private String paddrAreacode;
	private String PAddr;
	private String email;
	private String tel1;
	private String ttel2;
	private String deliTel;
	private Integer prepaid;
	private Long coPrice;
	private String vatNo;
	private String vatTitle;
	private String cardNo;
	private String cardMmyy;
	private String cardCrc;
	private String iaStatus;
	private String tssId;
	private String tssStaus;
	private String bogStatus;
	private String coStage;
	private String coAction;
	private String coStatus;
	private String cancel;
	private String tssMemo;
	private Character tssExtend;
	private Date tssExpireDay;
	private String coChange;
	private String simcardNo;
	private Character saflag;
	private Character npflag;
	private String txId;
	private Date activationDate;
	private Date shipDate;
	private Date arrivalDate;
	private Date soldDate;
	private String promotioncode;
	private String promoName;
	private String voiceplanId;
	private String loyaltyLevel;
	private String msisdn;
	private Character isExtend;
	private String extendEmpNo;
	private Date extendExpireDate;
	private Character isExceptOrder;
	private Character coSubsType;
	private Character isExported;
	private String DOfferid;
	private Character keepMsisdn;
	private String refundMemo;
	private String loyaltyCompany;
	private Date statusChangeDate;
	private String extraservice;
	private String laddress;
	private String lzipcode;
	private String token;
	private Date problemOrderDate;
	private Character fake3g;
	private String soasn;
	private Date portinDate;
	private String npStatus;
	private String npCompanyCode;
	private Byte installmentTenor;
	private Character isBundle;
	private Long einvoiceId;
	private String deliRocid;
	private String actiNo;
	private Character churnIndex;
	private Integer arpb;
	private String deliTel1;
	private Date promotionOnsaleDate;
	private Date bsMailingTime;
	private Long bundleIdentifier;
	private String isBillingtypeSent;
	private Integer oldBillingTypeId;
	private Integer newBillingTypeId;
	private String bundleId;
	private String packId;
	private Character isInvoiceDemand;
	private String deliReceiver;
	private String deliEmail;
	private String invoiceNo;
	private Character exclusiveOrder;
	private Character preSubscribeOrder;
	private String ivrCode;
	private String channel;
	private String onsalePromoListId;
	private Character isIphone;
	private String addOnMsisdn;
	private String vatAddress;
	private String vatAreacode;
	private Character addOnDeliAddr;
	private Character addOnInvoiceAddr;
	private Character addOnReceiver;
	private String subscriberNo;
	private Long webPosId;
	private String shipmentNo;
	private String einvoiceDeviceType;
	private String einvoiceDeviceId;
	private String donateUnitId;
	private String invoiceType;
	private Character three2Four;
	private Character fake4g;
	private String preorderNo;
	private String orderChannel;
	private String subscriberId;
	private String recommendDesc;
	private String recommendSource;
	private String eformTransId;
	private String eformResult;
	private Character isAuction;
	private String appSource;
	private String loyaltyUpgradeType;
	private Character waiveContract;
	private String returnStatus;
	private String mvpnVatNo;
	private String o2oOrderId;
	private Character transToO2o;
	private Character isIaUpdate;
	private String paymentConsolidation;
	private Date idCardDate;
	private String idCardCity;
	private String idCardType;
	private Character isMultiprod;
	private String cohOrderId;
	private String mdmAccountId;
	private String mdmSubscriberId;
	private String mdmCustomerId;
	private String mdmSixId;
	private Character ignoreTwid;
	private Character syncMdm;
	private BigDecimal timesToTry;
	private BigDecimal timesTried;
	private String batchType;
	private String status;
	private Date submitTime;
	private Character isSendCrm;

	public NbaCoMaster() {
	}

	public NbaCoMaster(String cono) {
		this.cono = cono;
	}

	public NbaCoMaster(String cono, String seq, Date coDate, String coType, String salesNo, String userId,
			String userName, String birthday, Character sex, String rocId, Character secDoc, String secId,
			Character payType, String virtualAcct, String reccipient, Character deliType, String storeno,
			Character companycode, String memo, Character deliAlt, Character deliTime, String deliAreacode,
			String deliAddr, String deliRemark, String billAreacode, String billAddr, String paddrAreacode,
			String PAddr, String email, String tel1, String ttel2, String deliTel, Integer prepaid, Long coPrice,
			String vatNo, String vatTitle, String cardNo, String cardMmyy, String cardCrc, String iaStatus,
			String tssId, String tssStaus, String bogStatus, String coStage, String coAction, String coStatus,
			String cancel, String tssMemo, Character tssExtend, Date tssExpireDay, String coChange, String simcardNo,
			Character saflag, Character npflag, String txId, Date activationDate, Date shipDate, Date arrivalDate,
			Date soldDate, String promotioncode, String promoName, String voiceplanId, String loyaltyLevel,
			String msisdn, Character isExtend, String extendEmpNo, Date extendExpireDate, Character isExceptOrder,
			Character coSubsType, Character isExported, String DOfferid, Character keepMsisdn, String refundMemo,
			String loyaltyCompany, Date statusChangeDate, String extraservice, String laddress, String lzipcode,
			String token, Date problemOrderDate, Character fake3g, String soasn, Date portinDate, String npStatus,
			String npCompanyCode, Byte installmentTenor, Character isBundle, Long einvoiceId, String deliRocid,
			String actiNo, Character churnIndex, Integer arpb, String deliTel1, Date promotionOnsaleDate,
			Date bsMailingTime, Long bundleIdentifier, String isBillingtypeSent, Integer oldBillingTypeId,
			Integer newBillingTypeId, String bundleId, String packId, Character isInvoiceDemand, String deliReceiver,
			String deliEmail, String invoiceNo, Character exclusiveOrder, Character preSubscribeOrder, String ivrCode,
			String channel, String onsalePromoListId, Character isIphone, String addOnMsisdn, String vatAddress,
			String vatAreacode, Character addOnDeliAddr, Character addOnInvoiceAddr, Character addOnReceiver,
			String subscriberNo, Long webPosId, String shipmentNo, String einvoiceDeviceType, String einvoiceDeviceId,
			String donateUnitId, String invoiceType, Character three2Four, Character fake4g, String preorderNo,
			String orderChannel, String subscriberId, String recommendDesc, String recommendSource, String eformTransId,
			String eformResult, Character isAuction, String appSource, String loyaltyUpgradeType,
			Character waiveContract, String returnStatus, String mvpnVatNo, String o2oOrderId, Character transToO2o,
			Character isIaUpdate, String paymentConsolidation, Date idCardDate, String idCardCity, String idCardType,
			Character isMultiprod, String cohOrderId, String mdmAccountId, String mdmSubscriberId, String mdmCustomerId,
			String mdmSixId, Character ignoreTwid, Character syncMdm, BigDecimal timesToTry, BigDecimal timesTried,
			String batchType, String status, Date submitTime, Character isSendCrm) {
		this.cono = cono;
		this.seq = seq;
		this.coDate = coDate;
		this.coType = coType;
		this.salesNo = salesNo;
		this.userId = userId;
		this.userName = userName;
		this.birthday = birthday;
		this.sex = sex;
		this.rocId = rocId;
		this.secDoc = secDoc;
		this.secId = secId;
		this.payType = payType;
		this.virtualAcct = virtualAcct;
		this.reccipient = reccipient;
		this.deliType = deliType;
		this.storeno = storeno;
		this.companycode = companycode;
		this.memo = memo;
		this.deliAlt = deliAlt;
		this.deliTime = deliTime;
		this.deliAreacode = deliAreacode;
		this.deliAddr = deliAddr;
		this.deliRemark = deliRemark;
		this.billAreacode = billAreacode;
		this.billAddr = billAddr;
		this.paddrAreacode = paddrAreacode;
		this.PAddr = PAddr;
		this.email = email;
		this.tel1 = tel1;
		this.ttel2 = ttel2;
		this.deliTel = deliTel;
		this.prepaid = prepaid;
		this.coPrice = coPrice;
		this.vatNo = vatNo;
		this.vatTitle = vatTitle;
		this.cardNo = cardNo;
		this.cardMmyy = cardMmyy;
		this.cardCrc = cardCrc;
		this.iaStatus = iaStatus;
		this.tssId = tssId;
		this.tssStaus = tssStaus;
		this.bogStatus = bogStatus;
		this.coStage = coStage;
		this.coAction = coAction;
		this.coStatus = coStatus;
		this.cancel = cancel;
		this.tssMemo = tssMemo;
		this.tssExtend = tssExtend;
		this.tssExpireDay = tssExpireDay;
		this.coChange = coChange;
		this.simcardNo = simcardNo;
		this.saflag = saflag;
		this.npflag = npflag;
		this.txId = txId;
		this.activationDate = activationDate;
		this.shipDate = shipDate;
		this.arrivalDate = arrivalDate;
		this.soldDate = soldDate;
		this.promotioncode = promotioncode;
		this.promoName = promoName;
		this.voiceplanId = voiceplanId;
		this.loyaltyLevel = loyaltyLevel;
		this.msisdn = msisdn;
		this.isExtend = isExtend;
		this.extendEmpNo = extendEmpNo;
		this.extendExpireDate = extendExpireDate;
		this.isExceptOrder = isExceptOrder;
		this.coSubsType = coSubsType;
		this.isExported = isExported;
		this.DOfferid = DOfferid;
		this.keepMsisdn = keepMsisdn;
		this.refundMemo = refundMemo;
		this.loyaltyCompany = loyaltyCompany;
		this.statusChangeDate = statusChangeDate;
		this.extraservice = extraservice;
		this.laddress = laddress;
		this.lzipcode = lzipcode;
		this.token = token;
		this.problemOrderDate = problemOrderDate;
		this.fake3g = fake3g;
		this.soasn = soasn;
		this.portinDate = portinDate;
		this.npStatus = npStatus;
		this.npCompanyCode = npCompanyCode;
		this.installmentTenor = installmentTenor;
		this.isBundle = isBundle;
		this.einvoiceId = einvoiceId;
		this.deliRocid = deliRocid;
		this.actiNo = actiNo;
		this.churnIndex = churnIndex;
		this.arpb = arpb;
		this.deliTel1 = deliTel1;
		this.promotionOnsaleDate = promotionOnsaleDate;
		this.bsMailingTime = bsMailingTime;
		this.bundleIdentifier = bundleIdentifier;
		this.isBillingtypeSent = isBillingtypeSent;
		this.oldBillingTypeId = oldBillingTypeId;
		this.newBillingTypeId = newBillingTypeId;
		this.bundleId = bundleId;
		this.packId = packId;
		this.isInvoiceDemand = isInvoiceDemand;
		this.deliReceiver = deliReceiver;
		this.deliEmail = deliEmail;
		this.invoiceNo = invoiceNo;
		this.exclusiveOrder = exclusiveOrder;
		this.preSubscribeOrder = preSubscribeOrder;
		this.ivrCode = ivrCode;
		this.channel = channel;
		this.onsalePromoListId = onsalePromoListId;
		this.isIphone = isIphone;
		this.addOnMsisdn = addOnMsisdn;
		this.vatAddress = vatAddress;
		this.vatAreacode = vatAreacode;
		this.addOnDeliAddr = addOnDeliAddr;
		this.addOnInvoiceAddr = addOnInvoiceAddr;
		this.addOnReceiver = addOnReceiver;
		this.subscriberNo = subscriberNo;
		this.webPosId = webPosId;
		this.shipmentNo = shipmentNo;
		this.einvoiceDeviceType = einvoiceDeviceType;
		this.einvoiceDeviceId = einvoiceDeviceId;
		this.donateUnitId = donateUnitId;
		this.invoiceType = invoiceType;
		this.three2Four = three2Four;
		this.fake4g = fake4g;
		this.preorderNo = preorderNo;
		this.orderChannel = orderChannel;
		this.subscriberId = subscriberId;
		this.recommendDesc = recommendDesc;
		this.recommendSource = recommendSource;
		this.eformTransId = eformTransId;
		this.eformResult = eformResult;
		this.isAuction = isAuction;
		this.appSource = appSource;
		this.loyaltyUpgradeType = loyaltyUpgradeType;
		this.waiveContract = waiveContract;
		this.returnStatus = returnStatus;
		this.mvpnVatNo = mvpnVatNo;
		this.o2oOrderId = o2oOrderId;
		this.transToO2o = transToO2o;
		this.isIaUpdate = isIaUpdate;
		this.paymentConsolidation = paymentConsolidation;
		this.idCardDate = idCardDate;
		this.idCardCity = idCardCity;
		this.idCardType = idCardType;
		this.isMultiprod = isMultiprod;
		this.cohOrderId = cohOrderId;
		this.mdmAccountId = mdmAccountId;
		this.mdmSubscriberId = mdmSubscriberId;
		this.mdmCustomerId = mdmCustomerId;
		this.mdmSixId = mdmSixId;
		this.ignoreTwid = ignoreTwid;
		this.syncMdm = syncMdm;
		this.timesToTry = timesToTry;
		this.timesTried = timesTried;
		this.batchType = batchType;
		this.status = status;
		this.submitTime = submitTime;
		this.isSendCrm = isSendCrm;
	}

	@Id

	@Column(name = "CONO", unique = true, nullable = false, length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "SEQ", length = 32)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CO_DATE", length = 7)
	public Date getCoDate() {
		return this.coDate;
	}

	public void setCoDate(Date coDate) {
		this.coDate = coDate;
	}

	@Column(name = "CO_TYPE", length = 2)
	public String getCoType() {
		return this.coType;
	}

	public void setCoType(String coType) {
		this.coType = coType;
	}

	@Column(name = "SALES_NO", length = 12)
	public String getSalesNo() {
		return this.salesNo;
	}

	public void setSalesNo(String salesNo) {
		this.salesNo = salesNo;
	}

	@Column(name = "USER_ID", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", length = 32)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "BIRTHDAY", length = 18)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "SEX", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "ROC_ID", length = 10)
	public String getRocId() {
		return this.rocId;
	}

	public void setRocId(String rocId) {
		this.rocId = rocId;
	}

	@Column(name = "SEC_DOC", length = 1)
	public Character getSecDoc() {
		return this.secDoc;
	}

	public void setSecDoc(Character secDoc) {
		this.secDoc = secDoc;
	}

	@Column(name = "SEC_ID", length = 30)
	public String getSecId() {
		return this.secId;
	}

	public void setSecId(String secId) {
		this.secId = secId;
	}

	@Column(name = "PAY_TYPE", length = 1)
	public Character getPayType() {
		return this.payType;
	}

	public void setPayType(Character payType) {
		this.payType = payType;
	}

	@Column(name = "VIRTUAL_ACCT", length = 32)
	public String getVirtualAcct() {
		return this.virtualAcct;
	}

	public void setVirtualAcct(String virtualAcct) {
		this.virtualAcct = virtualAcct;
	}

	@Column(name = "RECCIPIENT", length = 50)
	public String getReccipient() {
		return this.reccipient;
	}

	public void setReccipient(String reccipient) {
		this.reccipient = reccipient;
	}

	@Column(name = "DELI_TYPE", length = 1)
	public Character getDeliType() {
		return this.deliType;
	}

	public void setDeliType(Character deliType) {
		this.deliType = deliType;
	}

	@Column(name = "STORENO", length = 10)
	public String getStoreno() {
		return this.storeno;
	}

	public void setStoreno(String storeno) {
		this.storeno = storeno;
	}

	@Column(name = "COMPANYCODE", length = 1)
	public Character getCompanycode() {
		return this.companycode;
	}

	public void setCompanycode(Character companycode) {
		this.companycode = companycode;
	}

	@Column(name = "MEMO", length = 400)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "DELI_ALT", length = 1)
	public Character getDeliAlt() {
		return this.deliAlt;
	}

	public void setDeliAlt(Character deliAlt) {
		this.deliAlt = deliAlt;
	}

	@Column(name = "DELI_TIME", length = 1)
	public Character getDeliTime() {
		return this.deliTime;
	}

	public void setDeliTime(Character deliTime) {
		this.deliTime = deliTime;
	}

	@Column(name = "DELI_AREACODE", length = 6)
	public String getDeliAreacode() {
		return this.deliAreacode;
	}

	public void setDeliAreacode(String deliAreacode) {
		this.deliAreacode = deliAreacode;
	}

	@Column(name = "DELI_ADDR", length = 200)
	public String getDeliAddr() {
		return this.deliAddr;
	}

	public void setDeliAddr(String deliAddr) {
		this.deliAddr = deliAddr;
	}

	@Column(name = "DELI_REMARK", length = 400)
	public String getDeliRemark() {
		return this.deliRemark;
	}

	public void setDeliRemark(String deliRemark) {
		this.deliRemark = deliRemark;
	}

	@Column(name = "BILL_AREACODE", length = 6)
	public String getBillAreacode() {
		return this.billAreacode;
	}

	public void setBillAreacode(String billAreacode) {
		this.billAreacode = billAreacode;
	}

	@Column(name = "BILL_ADDR", length = 200)
	public String getBillAddr() {
		return this.billAddr;
	}

	public void setBillAddr(String billAddr) {
		this.billAddr = billAddr;
	}

	@Column(name = "PADDR_AREACODE", length = 6)
	public String getPaddrAreacode() {
		return this.paddrAreacode;
	}

	public void setPaddrAreacode(String paddrAreacode) {
		this.paddrAreacode = paddrAreacode;
	}

	@Column(name = "P_ADDR", length = 200)
	public String getPAddr() {
		return this.PAddr;
	}

	public void setPAddr(String PAddr) {
		this.PAddr = PAddr;
	}

	@Column(name = "EMAIL", length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TEL1", length = 20)
	public String getTel1() {
		return this.tel1;
	}

	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	@Column(name = "TTEL2", length = 20)
	public String getTtel2() {
		return this.ttel2;
	}

	public void setTtel2(String ttel2) {
		this.ttel2 = ttel2;
	}

	@Column(name = "DELI_TEL", length = 20)
	public String getDeliTel() {
		return this.deliTel;
	}

	public void setDeliTel(String deliTel) {
		this.deliTel = deliTel;
	}

	@Column(name = "PREPAID", precision = 5, scale = 0)
	public Integer getPrepaid() {
		return this.prepaid;
	}

	public void setPrepaid(Integer prepaid) {
		this.prepaid = prepaid;
	}

	@Column(name = "CO_PRICE", precision = 11, scale = 0)
	public Long getCoPrice() {
		return this.coPrice;
	}

	public void setCoPrice(Long coPrice) {
		this.coPrice = coPrice;
	}

	@Column(name = "VAT_NO", length = 8)
	public String getVatNo() {
		return this.vatNo;
	}

	public void setVatNo(String vatNo) {
		this.vatNo = vatNo;
	}

	@Column(name = "VAT_TITLE", length = 200)
	public String getVatTitle() {
		return this.vatTitle;
	}

	public void setVatTitle(String vatTitle) {
		this.vatTitle = vatTitle;
	}

	@Column(name = "CARD_NO", length = 16)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "CARD_MMYY", length = 4)
	public String getCardMmyy() {
		return this.cardMmyy;
	}

	public void setCardMmyy(String cardMmyy) {
		this.cardMmyy = cardMmyy;
	}

	@Column(name = "CARD_CRC", length = 3)
	public String getCardCrc() {
		return this.cardCrc;
	}

	public void setCardCrc(String cardCrc) {
		this.cardCrc = cardCrc;
	}

	@Column(name = "IA_STATUS", length = 5)
	public String getIaStatus() {
		return this.iaStatus;
	}

	public void setIaStatus(String iaStatus) {
		this.iaStatus = iaStatus;
	}

	@Column(name = "TSS_ID", length = 20)
	public String getTssId() {
		return this.tssId;
	}

	public void setTssId(String tssId) {
		this.tssId = tssId;
	}

	@Column(name = "TSS_STAUS", length = 5)
	public String getTssStaus() {
		return this.tssStaus;
	}

	public void setTssStaus(String tssStaus) {
		this.tssStaus = tssStaus;
	}

	@Column(name = "BOG_STATUS", length = 5)
	public String getBogStatus() {
		return this.bogStatus;
	}

	public void setBogStatus(String bogStatus) {
		this.bogStatus = bogStatus;
	}

	@Column(name = "CO_STAGE", length = 5)
	public String getCoStage() {
		return this.coStage;
	}

	public void setCoStage(String coStage) {
		this.coStage = coStage;
	}

	@Column(name = "CO_ACTION", length = 5)
	public String getCoAction() {
		return this.coAction;
	}

	public void setCoAction(String coAction) {
		this.coAction = coAction;
	}

	@Column(name = "CO_STATUS", length = 5)
	public String getCoStatus() {
		return this.coStatus;
	}

	public void setCoStatus(String coStatus) {
		this.coStatus = coStatus;
	}

	@Column(name = "CANCEL", length = 2)
	public String getCancel() {
		return this.cancel;
	}

	public void setCancel(String cancel) {
		this.cancel = cancel;
	}

	@Column(name = "TSS_MEMO", length = 1000)
	public String getTssMemo() {
		return this.tssMemo;
	}

	public void setTssMemo(String tssMemo) {
		this.tssMemo = tssMemo;
	}

	@Column(name = "TSS_EXTEND", length = 1)
	public Character getTssExtend() {
		return this.tssExtend;
	}

	public void setTssExtend(Character tssExtend) {
		this.tssExtend = tssExtend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TSS_EXPIRE_DAY", length = 7)
	public Date getTssExpireDay() {
		return this.tssExpireDay;
	}

	public void setTssExpireDay(Date tssExpireDay) {
		this.tssExpireDay = tssExpireDay;
	}

	@Column(name = "CO_CHANGE", length = 20)
	public String getCoChange() {
		return this.coChange;
	}

	public void setCoChange(String coChange) {
		this.coChange = coChange;
	}

	@Column(name = "SIMCARD_NO", length = 20)
	public String getSimcardNo() {
		return this.simcardNo;
	}

	public void setSimcardNo(String simcardNo) {
		this.simcardNo = simcardNo;
	}

	@Column(name = "SAFLAG", length = 1)
	public Character getSaflag() {
		return this.saflag;
	}

	public void setSaflag(Character saflag) {
		this.saflag = saflag;
	}

	@Column(name = "NPFLAG", length = 1)
	public Character getNpflag() {
		return this.npflag;
	}

	public void setNpflag(Character npflag) {
		this.npflag = npflag;
	}

	@Column(name = "TX_ID", length = 32)
	public String getTxId() {
		return this.txId;
	}

	public void setTxId(String txId) {
		this.txId = txId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACTIVATION_DATE", length = 7)
	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SHIP_DATE", length = 7)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ARRIVAL_DATE", length = 7)
	public Date getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SOLD_DATE", length = 7)
	public Date getSoldDate() {
		return this.soldDate;
	}

	public void setSoldDate(Date soldDate) {
		this.soldDate = soldDate;
	}

	@Column(name = "PROMOTIONCODE", length = 20)
	public String getPromotioncode() {
		return this.promotioncode;
	}

	public void setPromotioncode(String promotioncode) {
		this.promotioncode = promotioncode;
	}

	@Column(name = "PROMO_NAME", length = 500)
	public String getPromoName() {
		return this.promoName;
	}

	public void setPromoName(String promoName) {
		this.promoName = promoName;
	}

	@Column(name = "VOICEPLAN_ID", length = 100)
	public String getVoiceplanId() {
		return this.voiceplanId;
	}

	public void setVoiceplanId(String voiceplanId) {
		this.voiceplanId = voiceplanId;
	}

	@Column(name = "LOYALTY_LEVEL", length = 100)
	public String getLoyaltyLevel() {
		return this.loyaltyLevel;
	}

	public void setLoyaltyLevel(String loyaltyLevel) {
		this.loyaltyLevel = loyaltyLevel;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "IS_EXTEND", length = 1)
	public Character getIsExtend() {
		return this.isExtend;
	}

	public void setIsExtend(Character isExtend) {
		this.isExtend = isExtend;
	}

	@Column(name = "EXTEND_EMP_NO", length = 32)
	public String getExtendEmpNo() {
		return this.extendEmpNo;
	}

	public void setExtendEmpNo(String extendEmpNo) {
		this.extendEmpNo = extendEmpNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXTEND_EXPIRE_DATE", length = 7)
	public Date getExtendExpireDate() {
		return this.extendExpireDate;
	}

	public void setExtendExpireDate(Date extendExpireDate) {
		this.extendExpireDate = extendExpireDate;
	}

	@Column(name = "IS_EXCEPT_ORDER", length = 1)
	public Character getIsExceptOrder() {
		return this.isExceptOrder;
	}

	public void setIsExceptOrder(Character isExceptOrder) {
		this.isExceptOrder = isExceptOrder;
	}

	@Column(name = "CO_SUBS_TYPE", length = 1)
	public Character getCoSubsType() {
		return this.coSubsType;
	}

	public void setCoSubsType(Character coSubsType) {
		this.coSubsType = coSubsType;
	}

	@Column(name = "IS_EXPORTED", length = 1)
	public Character getIsExported() {
		return this.isExported;
	}

	public void setIsExported(Character isExported) {
		this.isExported = isExported;
	}

	@Column(name = "D_OFFERID", length = 30)
	public String getDOfferid() {
		return this.DOfferid;
	}

	public void setDOfferid(String DOfferid) {
		this.DOfferid = DOfferid;
	}

	@Column(name = "KEEP_MSISDN", length = 1)
	public Character getKeepMsisdn() {
		return this.keepMsisdn;
	}

	public void setKeepMsisdn(Character keepMsisdn) {
		this.keepMsisdn = keepMsisdn;
	}

	@Column(name = "REFUND_MEMO", length = 250)
	public String getRefundMemo() {
		return this.refundMemo;
	}

	public void setRefundMemo(String refundMemo) {
		this.refundMemo = refundMemo;
	}

	@Column(name = "LOYALTY_COMPANY", length = 5)
	public String getLoyaltyCompany() {
		return this.loyaltyCompany;
	}

	public void setLoyaltyCompany(String loyaltyCompany) {
		this.loyaltyCompany = loyaltyCompany;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STATUS_CHANGE_DATE", length = 7)
	public Date getStatusChangeDate() {
		return this.statusChangeDate;
	}

	public void setStatusChangeDate(Date statusChangeDate) {
		this.statusChangeDate = statusChangeDate;
	}

	@Column(name = "EXTRASERVICE", length = 200)
	public String getExtraservice() {
		return this.extraservice;
	}

	public void setExtraservice(String extraservice) {
		this.extraservice = extraservice;
	}

	@Column(name = "LADDRESS", length = 200)
	public String getLaddress() {
		return this.laddress;
	}

	public void setLaddress(String laddress) {
		this.laddress = laddress;
	}

	@Column(name = "LZIPCODE", length = 6)
	public String getLzipcode() {
		return this.lzipcode;
	}

	public void setLzipcode(String lzipcode) {
		this.lzipcode = lzipcode;
	}

	@Column(name = "TOKEN", length = 40)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PROBLEM_ORDER_DATE", length = 7)
	public Date getProblemOrderDate() {
		return this.problemOrderDate;
	}

	public void setProblemOrderDate(Date problemOrderDate) {
		this.problemOrderDate = problemOrderDate;
	}

	@Column(name = "FAKE3G", length = 1)
	public Character getFake3g() {
		return this.fake3g;
	}

	public void setFake3g(Character fake3g) {
		this.fake3g = fake3g;
	}

	@Column(name = "SOASN", length = 32)
	public String getSoasn() {
		return this.soasn;
	}

	public void setSoasn(String soasn) {
		this.soasn = soasn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PORTIN_DATE", length = 7)
	public Date getPortinDate() {
		return this.portinDate;
	}

	public void setPortinDate(Date portinDate) {
		this.portinDate = portinDate;
	}

	@Column(name = "NP_STATUS", length = 5)
	public String getNpStatus() {
		return this.npStatus;
	}

	public void setNpStatus(String npStatus) {
		this.npStatus = npStatus;
	}

	@Column(name = "NP_COMPANY_CODE", length = 3)
	public String getNpCompanyCode() {
		return this.npCompanyCode;
	}

	public void setNpCompanyCode(String npCompanyCode) {
		this.npCompanyCode = npCompanyCode;
	}

	@Column(name = "INSTALLMENT_TENOR", precision = 2, scale = 0)
	public Byte getInstallmentTenor() {
		return this.installmentTenor;
	}

	public void setInstallmentTenor(Byte installmentTenor) {
		this.installmentTenor = installmentTenor;
	}

	@Column(name = "IS_BUNDLE", length = 1)
	public Character getIsBundle() {
		return this.isBundle;
	}

	public void setIsBundle(Character isBundle) {
		this.isBundle = isBundle;
	}

	@Column(name = "EINVOICE_ID", precision = 15, scale = 0)
	public Long getEinvoiceId() {
		return this.einvoiceId;
	}

	public void setEinvoiceId(Long einvoiceId) {
		this.einvoiceId = einvoiceId;
	}

	@Column(name = "DELI_ROCID", length = 20)
	public String getDeliRocid() {
		return this.deliRocid;
	}

	public void setDeliRocid(String deliRocid) {
		this.deliRocid = deliRocid;
	}

	@Column(name = "ACTI_NO", length = 15)
	public String getActiNo() {
		return this.actiNo;
	}

	public void setActiNo(String actiNo) {
		this.actiNo = actiNo;
	}

	@Column(name = "CHURN_INDEX", length = 1)
	public Character getChurnIndex() {
		return this.churnIndex;
	}

	public void setChurnIndex(Character churnIndex) {
		this.churnIndex = churnIndex;
	}

	@Column(name = "ARPB", precision = 7, scale = 0)
	public Integer getArpb() {
		return this.arpb;
	}

	public void setArpb(Integer arpb) {
		this.arpb = arpb;
	}

	@Column(name = "DELI_TEL1", length = 20)
	public String getDeliTel1() {
		return this.deliTel1;
	}

	public void setDeliTel1(String deliTel1) {
		this.deliTel1 = deliTel1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PROMOTION_ONSALE_DATE", length = 7)
	public Date getPromotionOnsaleDate() {
		return this.promotionOnsaleDate;
	}

	public void setPromotionOnsaleDate(Date promotionOnsaleDate) {
		this.promotionOnsaleDate = promotionOnsaleDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BS_MAILING_TIME", length = 7)
	public Date getBsMailingTime() {
		return this.bsMailingTime;
	}

	public void setBsMailingTime(Date bsMailingTime) {
		this.bsMailingTime = bsMailingTime;
	}

	@Column(name = "BUNDLE_IDENTIFIER", precision = 12, scale = 0)
	public Long getBundleIdentifier() {
		return this.bundleIdentifier;
	}

	public void setBundleIdentifier(Long bundleIdentifier) {
		this.bundleIdentifier = bundleIdentifier;
	}

	@Column(name = "IS_BILLINGTYPE_SENT", length = 1)
	public String getIsBillingtypeSent() {
		return this.isBillingtypeSent;
	}

	public void setIsBillingtypeSent(String isBillingtypeSent) {
		this.isBillingtypeSent = isBillingtypeSent;
	}

	@Column(name = "OLD_BILLING_TYPE_ID", precision = 5, scale = 0)
	public Integer getOldBillingTypeId() {
		return this.oldBillingTypeId;
	}

	public void setOldBillingTypeId(Integer oldBillingTypeId) {
		this.oldBillingTypeId = oldBillingTypeId;
	}

	@Column(name = "NEW_BILLING_TYPE_ID", precision = 5, scale = 0)
	public Integer getNewBillingTypeId() {
		return this.newBillingTypeId;
	}

	public void setNewBillingTypeId(Integer newBillingTypeId) {
		this.newBillingTypeId = newBillingTypeId;
	}

	@Column(name = "BUNDLE_ID", length = 20)
	public String getBundleId() {
		return this.bundleId;
	}

	public void setBundleId(String bundleId) {
		this.bundleId = bundleId;
	}

	@Column(name = "PACK_ID", length = 20)
	public String getPackId() {
		return this.packId;
	}

	public void setPackId(String packId) {
		this.packId = packId;
	}

	@Column(name = "IS_INVOICE_DEMAND", length = 1)
	public Character getIsInvoiceDemand() {
		return this.isInvoiceDemand;
	}

	public void setIsInvoiceDemand(Character isInvoiceDemand) {
		this.isInvoiceDemand = isInvoiceDemand;
	}

	@Column(name = "DELI_RECEIVER", length = 24)
	public String getDeliReceiver() {
		return this.deliReceiver;
	}

	public void setDeliReceiver(String deliReceiver) {
		this.deliReceiver = deliReceiver;
	}

	@Column(name = "DELI_EMAIL", length = 80)
	public String getDeliEmail() {
		return this.deliEmail;
	}

	public void setDeliEmail(String deliEmail) {
		this.deliEmail = deliEmail;
	}

	@Column(name = "INVOICE_NO", length = 20)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "EXCLUSIVE_ORDER", length = 1)
	public Character getExclusiveOrder() {
		return this.exclusiveOrder;
	}

	public void setExclusiveOrder(Character exclusiveOrder) {
		this.exclusiveOrder = exclusiveOrder;
	}

	@Column(name = "PRE_SUBSCRIBE_ORDER", length = 1)
	public Character getPreSubscribeOrder() {
		return this.preSubscribeOrder;
	}

	public void setPreSubscribeOrder(Character preSubscribeOrder) {
		this.preSubscribeOrder = preSubscribeOrder;
	}

	@Column(name = "IVR_CODE", length = 20)
	public String getIvrCode() {
		return this.ivrCode;
	}

	public void setIvrCode(String ivrCode) {
		this.ivrCode = ivrCode;
	}

	@Column(name = "CHANNEL", length = 20)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "ONSALE_PROMO_LIST_ID", length = 32)
	public String getOnsalePromoListId() {
		return this.onsalePromoListId;
	}

	public void setOnsalePromoListId(String onsalePromoListId) {
		this.onsalePromoListId = onsalePromoListId;
	}

	@Column(name = "IS_IPHONE", length = 1)
	public Character getIsIphone() {
		return this.isIphone;
	}

	public void setIsIphone(Character isIphone) {
		this.isIphone = isIphone;
	}

	@Column(name = "ADD_ON_MSISDN", length = 10)
	public String getAddOnMsisdn() {
		return this.addOnMsisdn;
	}

	public void setAddOnMsisdn(String addOnMsisdn) {
		this.addOnMsisdn = addOnMsisdn;
	}

	@Column(name = "VAT_ADDRESS", length = 200)
	public String getVatAddress() {
		return this.vatAddress;
	}

	public void setVatAddress(String vatAddress) {
		this.vatAddress = vatAddress;
	}

	@Column(name = "VAT_AREACODE", length = 6)
	public String getVatAreacode() {
		return this.vatAreacode;
	}

	public void setVatAreacode(String vatAreacode) {
		this.vatAreacode = vatAreacode;
	}

	@Column(name = "ADD_ON_DELI_ADDR", length = 1)
	public Character getAddOnDeliAddr() {
		return this.addOnDeliAddr;
	}

	public void setAddOnDeliAddr(Character addOnDeliAddr) {
		this.addOnDeliAddr = addOnDeliAddr;
	}

	@Column(name = "ADD_ON_INVOICE_ADDR", length = 1)
	public Character getAddOnInvoiceAddr() {
		return this.addOnInvoiceAddr;
	}

	public void setAddOnInvoiceAddr(Character addOnInvoiceAddr) {
		this.addOnInvoiceAddr = addOnInvoiceAddr;
	}

	@Column(name = "ADD_ON_RECEIVER", length = 1)
	public Character getAddOnReceiver() {
		return this.addOnReceiver;
	}

	public void setAddOnReceiver(Character addOnReceiver) {
		this.addOnReceiver = addOnReceiver;
	}

	@Column(name = "SUBSCRIBER_NO", length = 20)
	public String getSubscriberNo() {
		return this.subscriberNo;
	}

	public void setSubscriberNo(String subscriberNo) {
		this.subscriberNo = subscriberNo;
	}

	@Column(name = "WEB_POS_ID", precision = 15, scale = 0)
	public Long getWebPosId() {
		return this.webPosId;
	}

	public void setWebPosId(Long webPosId) {
		this.webPosId = webPosId;
	}

	@Column(name = "SHIPMENT_NO", length = 32)
	public String getShipmentNo() {
		return this.shipmentNo;
	}

	public void setShipmentNo(String shipmentNo) {
		this.shipmentNo = shipmentNo;
	}

	@Column(name = "EINVOICE_DEVICE_TYPE", length = 10)
	public String getEinvoiceDeviceType() {
		return this.einvoiceDeviceType;
	}

	public void setEinvoiceDeviceType(String einvoiceDeviceType) {
		this.einvoiceDeviceType = einvoiceDeviceType;
	}

	@Column(name = "EINVOICE_DEVICE_ID", length = 32)
	public String getEinvoiceDeviceId() {
		return this.einvoiceDeviceId;
	}

	public void setEinvoiceDeviceId(String einvoiceDeviceId) {
		this.einvoiceDeviceId = einvoiceDeviceId;
	}

	@Column(name = "DONATE_UNIT_ID", length = 32)
	public String getDonateUnitId() {
		return this.donateUnitId;
	}

	public void setDonateUnitId(String donateUnitId) {
		this.donateUnitId = donateUnitId;
	}

	@Column(name = "INVOICE_TYPE", length = 20)
	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	@Column(name = "THREE_2_FOUR", length = 1)
	public Character getThree2Four() {
		return this.three2Four;
	}

	public void setThree2Four(Character three2Four) {
		this.three2Four = three2Four;
	}

	@Column(name = "FAKE4G", length = 1)
	public Character getFake4g() {
		return this.fake4g;
	}

	public void setFake4g(Character fake4g) {
		this.fake4g = fake4g;
	}

	@Column(name = "PREORDER_NO", length = 30)
	public String getPreorderNo() {
		return this.preorderNo;
	}

	public void setPreorderNo(String preorderNo) {
		this.preorderNo = preorderNo;
	}

	@Column(name = "ORDER_CHANNEL", length = 10)
	public String getOrderChannel() {
		return this.orderChannel;
	}

	public void setOrderChannel(String orderChannel) {
		this.orderChannel = orderChannel;
	}

	@Column(name = "SUBSCRIBER_ID", length = 20)
	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	@Column(name = "RECOMMEND_DESC", length = 200)
	public String getRecommendDesc() {
		return this.recommendDesc;
	}

	public void setRecommendDesc(String recommendDesc) {
		this.recommendDesc = recommendDesc;
	}

	@Column(name = "RECOMMEND_SOURCE", length = 2)
	public String getRecommendSource() {
		return this.recommendSource;
	}

	public void setRecommendSource(String recommendSource) {
		this.recommendSource = recommendSource;
	}

	@Column(name = "EFORM_TRANS_ID", length = 50)
	public String getEformTransId() {
		return this.eformTransId;
	}

	public void setEformTransId(String eformTransId) {
		this.eformTransId = eformTransId;
	}

	@Column(name = "EFORM_RESULT", length = 4000)
	public String getEformResult() {
		return this.eformResult;
	}

	public void setEformResult(String eformResult) {
		this.eformResult = eformResult;
	}

	@Column(name = "IS_AUCTION", length = 1)
	public Character getIsAuction() {
		return this.isAuction;
	}

	public void setIsAuction(Character isAuction) {
		this.isAuction = isAuction;
	}

	@Column(name = "APP_SOURCE", length = 20)
	public String getAppSource() {
		return this.appSource;
	}

	public void setAppSource(String appSource) {
		this.appSource = appSource;
	}

	@Column(name = "LOYALTY_UPGRADE_TYPE", length = 20)
	public String getLoyaltyUpgradeType() {
		return this.loyaltyUpgradeType;
	}

	public void setLoyaltyUpgradeType(String loyaltyUpgradeType) {
		this.loyaltyUpgradeType = loyaltyUpgradeType;
	}

	@Column(name = "WAIVE_CONTRACT", length = 1)
	public Character getWaiveContract() {
		return this.waiveContract;
	}

	public void setWaiveContract(Character waiveContract) {
		this.waiveContract = waiveContract;
	}

	@Column(name = "RETURN_STATUS", length = 4)
	public String getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(String returnStatus) {
		this.returnStatus = returnStatus;
	}

	@Column(name = "MVPN_VAT_NO", length = 200)
	public String getMvpnVatNo() {
		return this.mvpnVatNo;
	}

	public void setMvpnVatNo(String mvpnVatNo) {
		this.mvpnVatNo = mvpnVatNo;
	}

	@Column(name = "O2O_ORDER_ID", length = 20)
	public String getO2oOrderId() {
		return this.o2oOrderId;
	}

	public void setO2oOrderId(String o2oOrderId) {
		this.o2oOrderId = o2oOrderId;
	}

	@Column(name = "TRANS_TO_O2O", length = 1)
	public Character getTransToO2o() {
		return this.transToO2o;
	}

	public void setTransToO2o(Character transToO2o) {
		this.transToO2o = transToO2o;
	}

	@Column(name = "IS_IA_UPDATE", length = 1)
	public Character getIsIaUpdate() {
		return this.isIaUpdate;
	}

	public void setIsIaUpdate(Character isIaUpdate) {
		this.isIaUpdate = isIaUpdate;
	}

	@Column(name = "PAYMENT_CONSOLIDATION", length = 10)
	public String getPaymentConsolidation() {
		return this.paymentConsolidation;
	}

	public void setPaymentConsolidation(String paymentConsolidation) {
		this.paymentConsolidation = paymentConsolidation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ID_CARD_DATE", length = 7)
	public Date getIdCardDate() {
		return this.idCardDate;
	}

	public void setIdCardDate(Date idCardDate) {
		this.idCardDate = idCardDate;
	}

	@Column(name = "ID_CARD_CITY", length = 10)
	public String getIdCardCity() {
		return this.idCardCity;
	}

	public void setIdCardCity(String idCardCity) {
		this.idCardCity = idCardCity;
	}

	@Column(name = "ID_CARD_TYPE", length = 10)
	public String getIdCardType() {
		return this.idCardType;
	}

	public void setIdCardType(String idCardType) {
		this.idCardType = idCardType;
	}

	@Column(name = "IS_MULTIPROD", length = 1)
	public Character getIsMultiprod() {
		return this.isMultiprod;
	}

	public void setIsMultiprod(Character isMultiprod) {
		this.isMultiprod = isMultiprod;
	}

	@Column(name = "COH_ORDER_ID", length = 20)
	public String getCohOrderId() {
		return this.cohOrderId;
	}

	public void setCohOrderId(String cohOrderId) {
		this.cohOrderId = cohOrderId;
	}

	@Column(name = "MDM_ACCOUNT_ID", length = 20)
	public String getMdmAccountId() {
		return this.mdmAccountId;
	}

	public void setMdmAccountId(String mdmAccountId) {
		this.mdmAccountId = mdmAccountId;
	}

	@Column(name = "MDM_SUBSCRIBER_ID", length = 20)
	public String getMdmSubscriberId() {
		return this.mdmSubscriberId;
	}

	public void setMdmSubscriberId(String mdmSubscriberId) {
		this.mdmSubscriberId = mdmSubscriberId;
	}

	@Column(name = "MDM_CUSTOMER_ID", length = 20)
	public String getMdmCustomerId() {
		return this.mdmCustomerId;
	}

	public void setMdmCustomerId(String mdmCustomerId) {
		this.mdmCustomerId = mdmCustomerId;
	}

	@Column(name = "MDM_SIX_ID", length = 400)
	public String getMdmSixId() {
		return this.mdmSixId;
	}

	public void setMdmSixId(String mdmSixId) {
		this.mdmSixId = mdmSixId;
	}

	@Column(name = "IGNORE_TWID", length = 1)
	public Character getIgnoreTwid() {
		return this.ignoreTwid;
	}

	public void setIgnoreTwid(Character ignoreTwid) {
		this.ignoreTwid = ignoreTwid;
	}

	@Column(name = "SYNC_MDM", length = 1)
	public Character getSyncMdm() {
		return this.syncMdm;
	}

	public void setSyncMdm(Character syncMdm) {
		this.syncMdm = syncMdm;
	}

	@Column(name = "TIMES_TO_TRY", precision = 22, scale = 0)
	public BigDecimal getTimesToTry() {
		return this.timesToTry;
	}

	public void setTimesToTry(BigDecimal timesToTry) {
		this.timesToTry = timesToTry;
	}

	@Column(name = "TIMES_TRIED", precision = 22, scale = 0)
	public BigDecimal getTimesTried() {
		return this.timesTried;
	}

	public void setTimesTried(BigDecimal timesTried) {
		this.timesTried = timesTried;
	}

	@Column(name = "BATCH_TYPE", length = 30)
	public String getBatchType() {
		return this.batchType;
	}

	public void setBatchType(String batchType) {
		this.batchType = batchType;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMIT_TIME", length = 7)
	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	@Column(name = "IS_SEND_CRM", length = 1)
	public Character getIsSendCrm() {
		return this.isSendCrm;
	}

	public void setIsSendCrm(Character isSendCrm) {
		this.isSendCrm = isSendCrm;
	}

}
