package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NbaNameList generated by hbm2java
 */
@Entity
@Table(name = "NBA_NAME_LIST")
public class NbaNameList implements java.io.Serializable {

	private long id;
	private Long nbaActivityId;
	private String msisdn;
	private String rocId;
	private String cono;

	public NbaNameList() {
	}

	public NbaNameList(long id) {
		this.id = id;
	}

	public NbaNameList(long id, Long nbaActivityId, String msisdn, String rocId, String cono) {
		this.id = id;
		this.nbaActivityId = nbaActivityId;
		this.msisdn = msisdn;
		this.rocId = rocId;
		this.cono = cono;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NBA_ACTIVITY_ID", precision = 15, scale = 0)
	public Long getNbaActivityId() {
		return this.nbaActivityId;
	}

	public void setNbaActivityId(Long nbaActivityId) {
		this.nbaActivityId = nbaActivityId;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "ROC_ID", length = 10)
	public String getRocId() {
		return this.rocId;
	}

	public void setRocId(String rocId) {
		this.rocId = rocId;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

}
