package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcrRecord generated by hbm2java
 */
@Entity
@Table(name = "OCR_RECORD")
public class OcrRecord implements java.io.Serializable {

	private long id;
	private String ocrName;
	private String ocrRocid;
	private String ocrCertType;
	private Date ocrBirthday;
	private String mdmInfo;
	private String cono;
	private String ocrAddress;
	private Byte ocrBarcodeNotMath;
	private String ocrSn;
	private String ocrBarcode;
	private String ocrName2;
	private String ocrRocid2;
	private String ocrName3;
	private String ocrRocid3;
	private String ocrAddress3;
	private String ocrSerial2;
	private String ocrSerial3;
	private Date ocrBirthday2;
	private Date ocrBirthday3;

	public OcrRecord() {
	}

	public OcrRecord(long id) {
		this.id = id;
	}

	public OcrRecord(long id, String ocrName, String ocrRocid, String ocrCertType, Date ocrBirthday, String mdmInfo,
			String cono, String ocrAddress, Byte ocrBarcodeNotMath, String ocrSn, String ocrBarcode, String ocrName2,
			String ocrRocid2, String ocrName3, String ocrRocid3, String ocrAddress3, String ocrSerial2,
			String ocrSerial3, Date ocrBirthday2, Date ocrBirthday3) {
		this.id = id;
		this.ocrName = ocrName;
		this.ocrRocid = ocrRocid;
		this.ocrCertType = ocrCertType;
		this.ocrBirthday = ocrBirthday;
		this.mdmInfo = mdmInfo;
		this.cono = cono;
		this.ocrAddress = ocrAddress;
		this.ocrBarcodeNotMath = ocrBarcodeNotMath;
		this.ocrSn = ocrSn;
		this.ocrBarcode = ocrBarcode;
		this.ocrName2 = ocrName2;
		this.ocrRocid2 = ocrRocid2;
		this.ocrName3 = ocrName3;
		this.ocrRocid3 = ocrRocid3;
		this.ocrAddress3 = ocrAddress3;
		this.ocrSerial2 = ocrSerial2;
		this.ocrSerial3 = ocrSerial3;
		this.ocrBirthday2 = ocrBirthday2;
		this.ocrBirthday3 = ocrBirthday3;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "OCR_NAME", length = 20)
	public String getOcrName() {
		return this.ocrName;
	}

	public void setOcrName(String ocrName) {
		this.ocrName = ocrName;
	}

	@Column(name = "OCR_ROCID", length = 20)
	public String getOcrRocid() {
		return this.ocrRocid;
	}

	public void setOcrRocid(String ocrRocid) {
		this.ocrRocid = ocrRocid;
	}

	@Column(name = "OCR_CERT_TYPE", length = 20)
	public String getOcrCertType() {
		return this.ocrCertType;
	}

	public void setOcrCertType(String ocrCertType) {
		this.ocrCertType = ocrCertType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OCR_BIRTHDAY", length = 7)
	public Date getOcrBirthday() {
		return this.ocrBirthday;
	}

	public void setOcrBirthday(Date ocrBirthday) {
		this.ocrBirthday = ocrBirthday;
	}

	@Column(name = "MDM_INFO", length = 4000)
	public String getMdmInfo() {
		return this.mdmInfo;
	}

	public void setMdmInfo(String mdmInfo) {
		this.mdmInfo = mdmInfo;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "OCR_ADDRESS", length = 400)
	public String getOcrAddress() {
		return this.ocrAddress;
	}

	public void setOcrAddress(String ocrAddress) {
		this.ocrAddress = ocrAddress;
	}

	@Column(name = "OCR_BARCODE_NOT_MATH", precision = 2, scale = 0)
	public Byte getOcrBarcodeNotMath() {
		return this.ocrBarcodeNotMath;
	}

	public void setOcrBarcodeNotMath(Byte ocrBarcodeNotMath) {
		this.ocrBarcodeNotMath = ocrBarcodeNotMath;
	}

	@Column(name = "OCR_SN", length = 20)
	public String getOcrSn() {
		return this.ocrSn;
	}

	public void setOcrSn(String ocrSn) {
		this.ocrSn = ocrSn;
	}

	@Column(name = "OCR_BARCODE", length = 20)
	public String getOcrBarcode() {
		return this.ocrBarcode;
	}

	public void setOcrBarcode(String ocrBarcode) {
		this.ocrBarcode = ocrBarcode;
	}

	@Column(name = "OCR_NAME_2", length = 20)
	public String getOcrName2() {
		return this.ocrName2;
	}

	public void setOcrName2(String ocrName2) {
		this.ocrName2 = ocrName2;
	}

	@Column(name = "OCR_ROCID_2", length = 20)
	public String getOcrRocid2() {
		return this.ocrRocid2;
	}

	public void setOcrRocid2(String ocrRocid2) {
		this.ocrRocid2 = ocrRocid2;
	}

	@Column(name = "OCR_NAME_3", length = 20)
	public String getOcrName3() {
		return this.ocrName3;
	}

	public void setOcrName3(String ocrName3) {
		this.ocrName3 = ocrName3;
	}

	@Column(name = "OCR_ROCID_3", length = 20)
	public String getOcrRocid3() {
		return this.ocrRocid3;
	}

	public void setOcrRocid3(String ocrRocid3) {
		this.ocrRocid3 = ocrRocid3;
	}

	@Column(name = "OCR_ADDRESS_3", length = 400)
	public String getOcrAddress3() {
		return this.ocrAddress3;
	}

	public void setOcrAddress3(String ocrAddress3) {
		this.ocrAddress3 = ocrAddress3;
	}

	@Column(name = "OCR_SERIAL_2", length = 20)
	public String getOcrSerial2() {
		return this.ocrSerial2;
	}

	public void setOcrSerial2(String ocrSerial2) {
		this.ocrSerial2 = ocrSerial2;
	}

	@Column(name = "OCR_SERIAL_3", length = 20)
	public String getOcrSerial3() {
		return this.ocrSerial3;
	}

	public void setOcrSerial3(String ocrSerial3) {
		this.ocrSerial3 = ocrSerial3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OCR_BIRTHDAY_2", length = 7)
	public Date getOcrBirthday2() {
		return this.ocrBirthday2;
	}

	public void setOcrBirthday2(Date ocrBirthday2) {
		this.ocrBirthday2 = ocrBirthday2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OCR_BIRTHDAY_3", length = 7)
	public Date getOcrBirthday3() {
		return this.ocrBirthday3;
	}

	public void setOcrBirthday3(Date ocrBirthday3) {
		this.ocrBirthday3 = ocrBirthday3;
	}

}
