package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalInformationBackup generated by hbm2java
 */
@Entity
@Table(name = "PERSONAL_INFORMATION_BACKUP")
public class PersonalInformationBackup implements java.io.Serializable {

	private PersonalInformationBackupId id;
	private String userName;
	private String rocId;
	private String email;
	private String deliTel;
	private String tel1;
	private String ttel2;
	private String deliAddr;
	private String birthday;
	private String reccipient;
	private String billAddr;
	private String PAddr;
	private String deliReceiver;
	private String deliEmail;
	private Date updateDate;
	private String msisdn;
	private String userMobile;
	private String chineseName;
	private String address;

	public PersonalInformationBackup() {
	}

	public PersonalInformationBackup(PersonalInformationBackupId id, Date updateDate) {
		this.id = id;
		this.updateDate = updateDate;
	}

	public PersonalInformationBackup(PersonalInformationBackupId id, String userName, String rocId, String email,
			String deliTel, String tel1, String ttel2, String deliAddr, String birthday, String reccipient,
			String billAddr, String PAddr, String deliReceiver, String deliEmail, Date updateDate, String msisdn,
			String userMobile, String chineseName, String address) {
		this.id = id;
		this.userName = userName;
		this.rocId = rocId;
		this.email = email;
		this.deliTel = deliTel;
		this.tel1 = tel1;
		this.ttel2 = ttel2;
		this.deliAddr = deliAddr;
		this.birthday = birthday;
		this.reccipient = reccipient;
		this.billAddr = billAddr;
		this.PAddr = PAddr;
		this.deliReceiver = deliReceiver;
		this.deliEmail = deliEmail;
		this.updateDate = updateDate;
		this.msisdn = msisdn;
		this.userMobile = userMobile;
		this.chineseName = chineseName;
		this.address = address;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 40)),
			@AttributeOverride(name = "tableName", column = @Column(name = "TABLE_NAME", nullable = false, length = 60)),
			@AttributeOverride(name = "tablePk", column = @Column(name = "TABLE_PK", nullable = false, length = 40)) })
	public PersonalInformationBackupId getId() {
		return this.id;
	}

	public void setId(PersonalInformationBackupId id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "ROC_ID", length = 100)
	public String getRocId() {
		return this.rocId;
	}

	public void setRocId(String rocId) {
		this.rocId = rocId;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DELI_TEL", length = 100)
	public String getDeliTel() {
		return this.deliTel;
	}

	public void setDeliTel(String deliTel) {
		this.deliTel = deliTel;
	}

	@Column(name = "TEL1", length = 100)
	public String getTel1() {
		return this.tel1;
	}

	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	@Column(name = "TTEL2", length = 100)
	public String getTtel2() {
		return this.ttel2;
	}

	public void setTtel2(String ttel2) {
		this.ttel2 = ttel2;
	}

	@Column(name = "DELI_ADDR", length = 250)
	public String getDeliAddr() {
		return this.deliAddr;
	}

	public void setDeliAddr(String deliAddr) {
		this.deliAddr = deliAddr;
	}

	@Column(name = "BIRTHDAY", length = 100)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "RECCIPIENT", length = 100)
	public String getReccipient() {
		return this.reccipient;
	}

	public void setReccipient(String reccipient) {
		this.reccipient = reccipient;
	}

	@Column(name = "BILL_ADDR", length = 250)
	public String getBillAddr() {
		return this.billAddr;
	}

	public void setBillAddr(String billAddr) {
		this.billAddr = billAddr;
	}

	@Column(name = "P_ADDR", length = 250)
	public String getPAddr() {
		return this.PAddr;
	}

	public void setPAddr(String PAddr) {
		this.PAddr = PAddr;
	}

	@Column(name = "DELI_RECEIVER", length = 100)
	public String getDeliReceiver() {
		return this.deliReceiver;
	}

	public void setDeliReceiver(String deliReceiver) {
		this.deliReceiver = deliReceiver;
	}

	@Column(name = "DELI_EMAIL", length = 100)
	public String getDeliEmail() {
		return this.deliEmail;
	}

	public void setDeliEmail(String deliEmail) {
		this.deliEmail = deliEmail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", nullable = false, length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "MSISDN", length = 100)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "USER_MOBILE", length = 100)
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "CHINESE_NAME", length = 100)
	public String getChineseName() {
		return this.chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	@Column(name = "ADDRESS", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
