package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalInformationBackupId generated by hbm2java
 */
@Embeddable
public class PersonalInformationBackupId implements java.io.Serializable {

	private String uuid;
	private String tableName;
	private String tablePk;

	public PersonalInformationBackupId() {
	}

	public PersonalInformationBackupId(String uuid, String tableName, String tablePk) {
		this.uuid = uuid;
		this.tableName = tableName;
		this.tablePk = tablePk;
	}

	@Column(name = "UUID", nullable = false, length = 40)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "TABLE_NAME", nullable = false, length = 60)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "TABLE_PK", nullable = false, length = 40)
	public String getTablePk() {
		return this.tablePk;
	}

	public void setTablePk(String tablePk) {
		this.tablePk = tablePk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalInformationBackupId))
			return false;
		PersonalInformationBackupId castOther = (PersonalInformationBackupId) other;

		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null
				&& this.getUuid().equals(castOther.getUuid())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTablePk() == castOther.getTablePk()) || (this.getTablePk() != null
						&& castOther.getTablePk() != null && this.getTablePk().equals(castOther.getTablePk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTablePk() == null ? 0 : this.getTablePk().hashCode());
		return result;
	}

}
