package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SosaTemp generated by hbm2java
 */
@Entity
@Table(name = "SOSA_TEMP")
public class SosaTemp implements java.io.Serializable {

	private long id;
	private String sono;
	private String storeno;
	private BigDecimal linenumber;
	private String saNo;
	private String motonum;
	private String compName;
	private String sourceType;
	private String promoteno;
	private String promotenoStartDate;

	public SosaTemp() {
	}

	public SosaTemp(long id) {
		this.id = id;
	}

	public SosaTemp(long id, String sono, String storeno, BigDecimal linenumber, String saNo, String motonum,
			String compName, String sourceType, String promoteno, String promotenoStartDate) {
		this.id = id;
		this.sono = sono;
		this.storeno = storeno;
		this.linenumber = linenumber;
		this.saNo = saNo;
		this.motonum = motonum;
		this.compName = compName;
		this.sourceType = sourceType;
		this.promoteno = promoteno;
		this.promotenoStartDate = promotenoStartDate;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "SONO", length = 20)
	public String getSono() {
		return this.sono;
	}

	public void setSono(String sono) {
		this.sono = sono;
	}

	@Column(name = "STORENO", length = 10)
	public String getStoreno() {
		return this.storeno;
	}

	public void setStoreno(String storeno) {
		this.storeno = storeno;
	}

	@Column(name = "LINENUMBER", precision = 22, scale = 0)
	public BigDecimal getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(BigDecimal linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "SA_NO", length = 20)
	public String getSaNo() {
		return this.saNo;
	}

	public void setSaNo(String saNo) {
		this.saNo = saNo;
	}

	@Column(name = "MOTONUM", length = 10)
	public String getMotonum() {
		return this.motonum;
	}

	public void setMotonum(String motonum) {
		this.motonum = motonum;
	}

	@Column(name = "COMP_NAME", length = 50)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "SOURCE_TYPE", length = 1)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "PROMOTENO", length = 12)
	public String getPromoteno() {
		return this.promoteno;
	}

	public void setPromoteno(String promoteno) {
		this.promoteno = promoteno;
	}

	@Column(name = "PROMOTENO_START_DATE", length = 12)
	public String getPromotenoStartDate() {
		return this.promotenoStartDate;
	}

	public void setPromotenoStartDate(String promotenoStartDate) {
		this.promotenoStartDate = promotenoStartDate;
	}

}
