package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SoTemp generated by hbm2java
 */
@Entity
@Table(name = "SO_TEMP")
public class SoTemp implements java.io.Serializable {

	private String sono;
	private String storeno;
	private String orderDate;
	private String salesNo;
	private String compName;
	private String recipient;
	private String unino;
	private String uniTitle;
	private String sex;
	private String payType;
	private String compTel;
	private String homeTel;
	private String motonum;
	private String deliFlag;
	private String deliStoreno;
	private String deliAddr;
	private String deliRemark;
	private String deliSeg;
	private String saflag;
	private String npflag;
	private BigDecimal totalamt;
	private BigDecimal invamt;
	private String promoteno;
	private String dwnflag;
	private Date dwndate;
	private Date senddate;
	private String mwTxid;
	private String subordertype;
	private String packageNo;
	private String preorderFlag;
	private String sourceType;
	private String einvoiceFlag;
	private String invoiceNo;
	private String invoiceDate;
	private String invoiceDoc;
	private String taxable;
	private String monopolyFlag;
	private String soid;
	private String convertmemo;
	private String dwnuser;
	private String email;
	private String postcode;
	private String donationunit;
	private Long einvoiceId;
	private String invoiceAddr;
	private String carriertype;
	private String carrierid1;
	private String carrierid2;
	private String id3;
	private String msisdnType;
	private String transId;
	private String mvpnFlag;
	private Character idcardFlag;
	private String secondidType;
	private String orderId;
	private String csStoreNo;
	private String csStoreName;
	private String csStoreAddress;
	private String csStoreAreacode;
	private String csName;
	private String csGetType;

	public SoTemp() {
	}

	public SoTemp(String sono, String storeno) {
		this.sono = sono;
		this.storeno = storeno;
	}

	public SoTemp(String sono, String storeno, String orderDate, String salesNo, String compName, String recipient,
			String unino, String uniTitle, String sex, String payType, String compTel, String homeTel, String motonum,
			String deliFlag, String deliStoreno, String deliAddr, String deliRemark, String deliSeg, String saflag,
			String npflag, BigDecimal totalamt, BigDecimal invamt, String promoteno, String dwnflag, Date dwndate,
			Date senddate, String mwTxid, String subordertype, String packageNo, String preorderFlag, String sourceType,
			String einvoiceFlag, String invoiceNo, String invoiceDate, String invoiceDoc, String taxable,
			String monopolyFlag, String soid, String convertmemo, String dwnuser, String email, String postcode,
			String donationunit, Long einvoiceId, String invoiceAddr, String carriertype, String carrierid1,
			String carrierid2, String id3, String msisdnType, String transId, String mvpnFlag, Character idcardFlag,
			String secondidType, String orderId, String csStoreNo, String csStoreName, String csStoreAddress,
			String csStoreAreacode, String csName, String csGetType) {
		this.sono = sono;
		this.storeno = storeno;
		this.orderDate = orderDate;
		this.salesNo = salesNo;
		this.compName = compName;
		this.recipient = recipient;
		this.unino = unino;
		this.uniTitle = uniTitle;
		this.sex = sex;
		this.payType = payType;
		this.compTel = compTel;
		this.homeTel = homeTel;
		this.motonum = motonum;
		this.deliFlag = deliFlag;
		this.deliStoreno = deliStoreno;
		this.deliAddr = deliAddr;
		this.deliRemark = deliRemark;
		this.deliSeg = deliSeg;
		this.saflag = saflag;
		this.npflag = npflag;
		this.totalamt = totalamt;
		this.invamt = invamt;
		this.promoteno = promoteno;
		this.dwnflag = dwnflag;
		this.dwndate = dwndate;
		this.senddate = senddate;
		this.mwTxid = mwTxid;
		this.subordertype = subordertype;
		this.packageNo = packageNo;
		this.preorderFlag = preorderFlag;
		this.sourceType = sourceType;
		this.einvoiceFlag = einvoiceFlag;
		this.invoiceNo = invoiceNo;
		this.invoiceDate = invoiceDate;
		this.invoiceDoc = invoiceDoc;
		this.taxable = taxable;
		this.monopolyFlag = monopolyFlag;
		this.soid = soid;
		this.convertmemo = convertmemo;
		this.dwnuser = dwnuser;
		this.email = email;
		this.postcode = postcode;
		this.donationunit = donationunit;
		this.einvoiceId = einvoiceId;
		this.invoiceAddr = invoiceAddr;
		this.carriertype = carriertype;
		this.carrierid1 = carrierid1;
		this.carrierid2 = carrierid2;
		this.id3 = id3;
		this.msisdnType = msisdnType;
		this.transId = transId;
		this.mvpnFlag = mvpnFlag;
		this.idcardFlag = idcardFlag;
		this.secondidType = secondidType;
		this.orderId = orderId;
		this.csStoreNo = csStoreNo;
		this.csStoreName = csStoreName;
		this.csStoreAddress = csStoreAddress;
		this.csStoreAreacode = csStoreAreacode;
		this.csName = csName;
		this.csGetType = csGetType;
	}

	@Id

	@Column(name = "SONO", unique = true, nullable = false, length = 20)
	public String getSono() {
		return this.sono;
	}

	public void setSono(String sono) {
		this.sono = sono;
	}

	@Column(name = "STORENO", nullable = false, length = 10)
	public String getStoreno() {
		return this.storeno;
	}

	public void setStoreno(String storeno) {
		this.storeno = storeno;
	}

	@Column(name = "ORDER_DATE", length = 8)
	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "SALES_NO", length = 10)
	public String getSalesNo() {
		return this.salesNo;
	}

	public void setSalesNo(String salesNo) {
		this.salesNo = salesNo;
	}

	@Column(name = "COMP_NAME", length = 50)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "RECIPIENT", length = 32)
	public String getRecipient() {
		return this.recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	@Column(name = "UNINO", length = 8)
	public String getUnino() {
		return this.unino;
	}

	public void setUnino(String unino) {
		this.unino = unino;
	}

	@Column(name = "UNI_TITLE", length = 50)
	public String getUniTitle() {
		return this.uniTitle;
	}

	public void setUniTitle(String uniTitle) {
		this.uniTitle = uniTitle;
	}

	@Column(name = "SEX", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "PAY_TYPE", length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "COMP_TEL", length = 20)
	public String getCompTel() {
		return this.compTel;
	}

	public void setCompTel(String compTel) {
		this.compTel = compTel;
	}

	@Column(name = "HOME_TEL", length = 20)
	public String getHomeTel() {
		return this.homeTel;
	}

	public void setHomeTel(String homeTel) {
		this.homeTel = homeTel;
	}

	@Column(name = "MOTONUM", length = 10)
	public String getMotonum() {
		return this.motonum;
	}

	public void setMotonum(String motonum) {
		this.motonum = motonum;
	}

	@Column(name = "DELI_FLAG", length = 1)
	public String getDeliFlag() {
		return this.deliFlag;
	}

	public void setDeliFlag(String deliFlag) {
		this.deliFlag = deliFlag;
	}

	@Column(name = "DELI_STORENO", length = 10)
	public String getDeliStoreno() {
		return this.deliStoreno;
	}

	public void setDeliStoreno(String deliStoreno) {
		this.deliStoreno = deliStoreno;
	}

	@Column(name = "DELI_ADDR", length = 100)
	public String getDeliAddr() {
		return this.deliAddr;
	}

	public void setDeliAddr(String deliAddr) {
		this.deliAddr = deliAddr;
	}

	@Column(name = "DELI_REMARK", length = 80)
	public String getDeliRemark() {
		return this.deliRemark;
	}

	public void setDeliRemark(String deliRemark) {
		this.deliRemark = deliRemark;
	}

	@Column(name = "DELI_SEG", length = 1)
	public String getDeliSeg() {
		return this.deliSeg;
	}

	public void setDeliSeg(String deliSeg) {
		this.deliSeg = deliSeg;
	}

	@Column(name = "SAFLAG", length = 1)
	public String getSaflag() {
		return this.saflag;
	}

	public void setSaflag(String saflag) {
		this.saflag = saflag;
	}

	@Column(name = "NPFLAG", length = 1)
	public String getNpflag() {
		return this.npflag;
	}

	public void setNpflag(String npflag) {
		this.npflag = npflag;
	}

	@Column(name = "TOTALAMT", scale = 4)
	public BigDecimal getTotalamt() {
		return this.totalamt;
	}

	public void setTotalamt(BigDecimal totalamt) {
		this.totalamt = totalamt;
	}

	@Column(name = "INVAMT", scale = 4)
	public BigDecimal getInvamt() {
		return this.invamt;
	}

	public void setInvamt(BigDecimal invamt) {
		this.invamt = invamt;
	}

	@Column(name = "PROMOTENO", length = 12)
	public String getPromoteno() {
		return this.promoteno;
	}

	public void setPromoteno(String promoteno) {
		this.promoteno = promoteno;
	}

	@Column(name = "DWNFLAG", length = 1)
	public String getDwnflag() {
		return this.dwnflag;
	}

	public void setDwnflag(String dwnflag) {
		this.dwnflag = dwnflag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DWNDATE", length = 7)
	public Date getDwndate() {
		return this.dwndate;
	}

	public void setDwndate(Date dwndate) {
		this.dwndate = dwndate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SENDDATE", length = 7)
	public Date getSenddate() {
		return this.senddate;
	}

	public void setSenddate(Date senddate) {
		this.senddate = senddate;
	}

	@Column(name = "MW_TXID", length = 25)
	public String getMwTxid() {
		return this.mwTxid;
	}

	public void setMwTxid(String mwTxid) {
		this.mwTxid = mwTxid;
	}

	@Column(name = "SUBORDERTYPE", length = 1)
	public String getSubordertype() {
		return this.subordertype;
	}

	public void setSubordertype(String subordertype) {
		this.subordertype = subordertype;
	}

	@Column(name = "PACKAGE_NO", length = 20)
	public String getPackageNo() {
		return this.packageNo;
	}

	public void setPackageNo(String packageNo) {
		this.packageNo = packageNo;
	}

	@Column(name = "PREORDER_FLAG", length = 1)
	public String getPreorderFlag() {
		return this.preorderFlag;
	}

	public void setPreorderFlag(String preorderFlag) {
		this.preorderFlag = preorderFlag;
	}

	@Column(name = "SOURCE_TYPE", length = 1)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "EINVOICE_FLAG", length = 1)
	public String getEinvoiceFlag() {
		return this.einvoiceFlag;
	}

	public void setEinvoiceFlag(String einvoiceFlag) {
		this.einvoiceFlag = einvoiceFlag;
	}

	@Column(name = "INVOICE_NO", length = 10)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "INVOICE_DATE", length = 8)
	public String getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(String invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "INVOICE_DOC", length = 1)
	public String getInvoiceDoc() {
		return this.invoiceDoc;
	}

	public void setInvoiceDoc(String invoiceDoc) {
		this.invoiceDoc = invoiceDoc;
	}

	@Column(name = "TAXABLE", length = 1)
	public String getTaxable() {
		return this.taxable;
	}

	public void setTaxable(String taxable) {
		this.taxable = taxable;
	}

	@Column(name = "MONOPOLY_FLAG", length = 1)
	public String getMonopolyFlag() {
		return this.monopolyFlag;
	}

	public void setMonopolyFlag(String monopolyFlag) {
		this.monopolyFlag = monopolyFlag;
	}

	@Column(name = "SOID", length = 18)
	public String getSoid() {
		return this.soid;
	}

	public void setSoid(String soid) {
		this.soid = soid;
	}

	@Column(name = "CONVERTMEMO", length = 100)
	public String getConvertmemo() {
		return this.convertmemo;
	}

	public void setConvertmemo(String convertmemo) {
		this.convertmemo = convertmemo;
	}

	@Column(name = "DWNUSER", length = 20)
	public String getDwnuser() {
		return this.dwnuser;
	}

	public void setDwnuser(String dwnuser) {
		this.dwnuser = dwnuser;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "POSTCODE", length = 6)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "DONATIONUNIT", length = 10)
	public String getDonationunit() {
		return this.donationunit;
	}

	public void setDonationunit(String donationunit) {
		this.donationunit = donationunit;
	}

	@Column(name = "EINVOICE_ID", precision = 15, scale = 0)
	public Long getEinvoiceId() {
		return this.einvoiceId;
	}

	public void setEinvoiceId(Long einvoiceId) {
		this.einvoiceId = einvoiceId;
	}

	@Column(name = "INVOICE_ADDR", length = 100)
	public String getInvoiceAddr() {
		return this.invoiceAddr;
	}

	public void setInvoiceAddr(String invoiceAddr) {
		this.invoiceAddr = invoiceAddr;
	}

	@Column(name = "CARRIERTYPE", length = 20)
	public String getCarriertype() {
		return this.carriertype;
	}

	public void setCarriertype(String carriertype) {
		this.carriertype = carriertype;
	}

	@Column(name = "CARRIERID1", length = 64)
	public String getCarrierid1() {
		return this.carrierid1;
	}

	public void setCarrierid1(String carrierid1) {
		this.carrierid1 = carrierid1;
	}

	@Column(name = "CARRIERID2", length = 64)
	public String getCarrierid2() {
		return this.carrierid2;
	}

	public void setCarrierid2(String carrierid2) {
		this.carrierid2 = carrierid2;
	}

	@Column(name = "ID3", length = 80)
	public String getId3() {
		return this.id3;
	}

	public void setId3(String id3) {
		this.id3 = id3;
	}

	@Column(name = "MSISDN_TYPE", length = 1)
	public String getMsisdnType() {
		return this.msisdnType;
	}

	public void setMsisdnType(String msisdnType) {
		this.msisdnType = msisdnType;
	}

	@Column(name = "TRANS_ID", length = 50)
	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	@Column(name = "MVPN_FLAG", length = 1)
	public String getMvpnFlag() {
		return this.mvpnFlag;
	}

	public void setMvpnFlag(String mvpnFlag) {
		this.mvpnFlag = mvpnFlag;
	}

	@Column(name = "IDCARD_FLAG", length = 1)
	public Character getIdcardFlag() {
		return this.idcardFlag;
	}

	public void setIdcardFlag(Character idcardFlag) {
		this.idcardFlag = idcardFlag;
	}

	@Column(name = "SECONDID_TYPE", length = 10)
	public String getSecondidType() {
		return this.secondidType;
	}

	public void setSecondidType(String secondidType) {
		this.secondidType = secondidType;
	}

	@Column(name = "ORDER_ID", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "CS_STORE_NO", length = 20)
	public String getCsStoreNo() {
		return this.csStoreNo;
	}

	public void setCsStoreNo(String csStoreNo) {
		this.csStoreNo = csStoreNo;
	}

	@Column(name = "CS_STORE_NAME", length = 400)
	public String getCsStoreName() {
		return this.csStoreName;
	}

	public void setCsStoreName(String csStoreName) {
		this.csStoreName = csStoreName;
	}

	@Column(name = "CS_STORE_ADDRESS", length = 400)
	public String getCsStoreAddress() {
		return this.csStoreAddress;
	}

	public void setCsStoreAddress(String csStoreAddress) {
		this.csStoreAddress = csStoreAddress;
	}

	@Column(name = "CS_STORE_AREACODE", length = 10)
	public String getCsStoreAreacode() {
		return this.csStoreAreacode;
	}

	public void setCsStoreAreacode(String csStoreAreacode) {
		this.csStoreAreacode = csStoreAreacode;
	}

	@Column(name = "CS_NAME", length = 20)
	public String getCsName() {
		return this.csName;
	}

	public void setCsName(String csName) {
		this.csName = csName;
	}

	@Column(name = "CS_GET_TYPE", length = 20)
	public String getCsGetType() {
		return this.csGetType;
	}

	public void setCsGetType(String csGetType) {
		this.csGetType = csGetType;
	}

}
