package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnavailableInformList generated by hbm2java
 */
@Entity
@Table(name = "UNAVAILABLE_INFORM_LIST")
public class UnavailableInformList implements java.io.Serializable {

	private long id;
	private String deviceType;
	private String fetNo;
	private String name;
	private Character gender;
	private String email;
	private String mobile;
	private Byte quantity;
	private String orderType;
	private Serializable createTime;
	private Boolean isInformed;
	private String productId;
	private Serializable informTime;
	private String loyaltyMsisdn;
	private String rocId;
	private String seq;
	private Byte timesToNotice;
	private String remark;
	private String linkUrl;
	private Long noticeMailTemplateId;
	private Boolean isMessageGenerate;
	private String noticeMailTemplateHistory;
	private Boolean isPreorderCancel;
	private Long preorderActivityId;
	private String preorderActivityName;
	private String giftFetNo;
	private String cono;
	private String source;
	private Boolean isForceClose;
	private Long preorderActId;
	private Character deliverType;

	public UnavailableInformList() {
	}

	public UnavailableInformList(long id) {
		this.id = id;
	}

	public UnavailableInformList(long id, String deviceType, String fetNo, String name, Character gender, String email,
			String mobile, Byte quantity, String orderType, Serializable createTime, Boolean isInformed,
			String productId, Serializable informTime, String loyaltyMsisdn, String rocId, String seq,
			Byte timesToNotice, String remark, String linkUrl, Long noticeMailTemplateId, Boolean isMessageGenerate,
			String noticeMailTemplateHistory, Boolean isPreorderCancel, Long preorderActivityId,
			String preorderActivityName, String giftFetNo, String cono, String source, Boolean isForceClose,
			Long preorderActId, Character deliverType) {
		this.id = id;
		this.deviceType = deviceType;
		this.fetNo = fetNo;
		this.name = name;
		this.gender = gender;
		this.email = email;
		this.mobile = mobile;
		this.quantity = quantity;
		this.orderType = orderType;
		this.createTime = createTime;
		this.isInformed = isInformed;
		this.productId = productId;
		this.informTime = informTime;
		this.loyaltyMsisdn = loyaltyMsisdn;
		this.rocId = rocId;
		this.seq = seq;
		this.timesToNotice = timesToNotice;
		this.remark = remark;
		this.linkUrl = linkUrl;
		this.noticeMailTemplateId = noticeMailTemplateId;
		this.isMessageGenerate = isMessageGenerate;
		this.noticeMailTemplateHistory = noticeMailTemplateHistory;
		this.isPreorderCancel = isPreorderCancel;
		this.preorderActivityId = preorderActivityId;
		this.preorderActivityName = preorderActivityName;
		this.giftFetNo = giftFetNo;
		this.cono = cono;
		this.source = source;
		this.isForceClose = isForceClose;
		this.preorderActId = preorderActId;
		this.deliverType = deliverType;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DEVICE_TYPE", length = 10)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "FET_NO", length = 20)
	public String getFetNo() {
		return this.fetNo;
	}

	public void setFetNo(String fetNo) {
		this.fetNo = fetNo;
	}

	@Column(name = "NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MOBILE", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "QUANTITY", precision = 2, scale = 0)
	public Byte getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Byte quantity) {
		this.quantity = quantity;
	}

	@Column(name = "ORDER_TYPE", length = 5)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "CREATE_TIME")
	public Serializable getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Serializable createTime) {
		this.createTime = createTime;
	}

	@Column(name = "IS_INFORMED", precision = 1, scale = 0)
	public Boolean getIsInformed() {
		return this.isInformed;
	}

	public void setIsInformed(Boolean isInformed) {
		this.isInformed = isInformed;
	}

	@Column(name = "PRODUCT_ID", length = 32)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "INFORM_TIME")
	public Serializable getInformTime() {
		return this.informTime;
	}

	public void setInformTime(Serializable informTime) {
		this.informTime = informTime;
	}

	@Column(name = "LOYALTY_MSISDN", length = 10)
	public String getLoyaltyMsisdn() {
		return this.loyaltyMsisdn;
	}

	public void setLoyaltyMsisdn(String loyaltyMsisdn) {
		this.loyaltyMsisdn = loyaltyMsisdn;
	}

	@Column(name = "ROC_ID", length = 10)
	public String getRocId() {
		return this.rocId;
	}

	public void setRocId(String rocId) {
		this.rocId = rocId;
	}

	@Column(name = "SEQ", length = 20)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "TIMES_TO_NOTICE", precision = 2, scale = 0)
	public Byte getTimesToNotice() {
		return this.timesToNotice;
	}

	public void setTimesToNotice(Byte timesToNotice) {
		this.timesToNotice = timesToNotice;
	}

	@Column(name = "REMARK", length = 4000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LINK_URL", length = 400)
	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	@Column(name = "NOTICE_MAIL_TEMPLATE_ID", precision = 15, scale = 0)
	public Long getNoticeMailTemplateId() {
		return this.noticeMailTemplateId;
	}

	public void setNoticeMailTemplateId(Long noticeMailTemplateId) {
		this.noticeMailTemplateId = noticeMailTemplateId;
	}

	@Column(name = "IS_MESSAGE_GENERATE", precision = 1, scale = 0)
	public Boolean getIsMessageGenerate() {
		return this.isMessageGenerate;
	}

	public void setIsMessageGenerate(Boolean isMessageGenerate) {
		this.isMessageGenerate = isMessageGenerate;
	}

	@Column(name = "NOTICE_MAIL_TEMPLATE_HISTORY", length = 2000)
	public String getNoticeMailTemplateHistory() {
		return this.noticeMailTemplateHistory;
	}

	public void setNoticeMailTemplateHistory(String noticeMailTemplateHistory) {
		this.noticeMailTemplateHistory = noticeMailTemplateHistory;
	}

	@Column(name = "IS_PREORDER_CANCEL", precision = 1, scale = 0)
	public Boolean getIsPreorderCancel() {
		return this.isPreorderCancel;
	}

	public void setIsPreorderCancel(Boolean isPreorderCancel) {
		this.isPreorderCancel = isPreorderCancel;
	}

	@Column(name = "PREORDER_ACTIVITY_ID", precision = 15, scale = 0)
	public Long getPreorderActivityId() {
		return this.preorderActivityId;
	}

	public void setPreorderActivityId(Long preorderActivityId) {
		this.preorderActivityId = preorderActivityId;
	}

	@Column(name = "PREORDER_ACTIVITY_NAME", length = 200)
	public String getPreorderActivityName() {
		return this.preorderActivityName;
	}

	public void setPreorderActivityName(String preorderActivityName) {
		this.preorderActivityName = preorderActivityName;
	}

	@Column(name = "GIFT_FET_NO", length = 100)
	public String getGiftFetNo() {
		return this.giftFetNo;
	}

	public void setGiftFetNo(String giftFetNo) {
		this.giftFetNo = giftFetNo;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "SOURCE", length = 10)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "IS_FORCE_CLOSE", precision = 1, scale = 0)
	public Boolean getIsForceClose() {
		return this.isForceClose;
	}

	public void setIsForceClose(Boolean isForceClose) {
		this.isForceClose = isForceClose;
	}

	@Column(name = "PREORDER_ACT_ID", precision = 15, scale = 0)
	public Long getPreorderActId() {
		return this.preorderActId;
	}

	public void setPreorderActId(Long preorderActId) {
		this.preorderActId = preorderActId;
	}

	@Column(name = "DELIVER_TYPE", length = 1)
	public Character getDeliverType() {
		return this.deliverType;
	}

	public void setDeliverType(Character deliverType) {
		this.deliverType = deliverType;
	}

}
