package com.fet.db.oracle.pojo;
// Generated 2020/12/25 �U�� 02:18:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UpgradePlusOrderId generated by hbm2java
 */
@Embeddable
public class UpgradePlusOrderId implements java.io.Serializable {

	private String cono;
	private String txid;
	private String subscriberId;
	private String accountId;
	private String userName;
	private String rocId;
	private String onsalePromoListId;
	private String msisdn;
	private Character isSendToLoyalty;
	private Date coDate;
	private String loyaltyResponseXml;
	private String initialOrderXml;
	private String updateEstoreDataResponse;
	private String lyConfirmOrderRequestXml;
	private String lyConfirmOrderResponseXml;
	private String cohOrderId;

	public UpgradePlusOrderId() {
	}

	public UpgradePlusOrderId(String cono, String txid, String subscriberId, String accountId, String userName,
			String rocId, String onsalePromoListId, String msisdn, Character isSendToLoyalty, Date coDate,
			String loyaltyResponseXml, String initialOrderXml, String updateEstoreDataResponse,
			String lyConfirmOrderRequestXml, String lyConfirmOrderResponseXml, String cohOrderId) {
		this.cono = cono;
		this.txid = txid;
		this.subscriberId = subscriberId;
		this.accountId = accountId;
		this.userName = userName;
		this.rocId = rocId;
		this.onsalePromoListId = onsalePromoListId;
		this.msisdn = msisdn;
		this.isSendToLoyalty = isSendToLoyalty;
		this.coDate = coDate;
		this.loyaltyResponseXml = loyaltyResponseXml;
		this.initialOrderXml = initialOrderXml;
		this.updateEstoreDataResponse = updateEstoreDataResponse;
		this.lyConfirmOrderRequestXml = lyConfirmOrderRequestXml;
		this.lyConfirmOrderResponseXml = lyConfirmOrderResponseXml;
		this.cohOrderId = cohOrderId;
	}

	@Column(name = "CONO", length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "TXID", length = 32)
	public String getTxid() {
		return this.txid;
	}

	public void setTxid(String txid) {
		this.txid = txid;
	}

	@Column(name = "SUBSCRIBER_ID", length = 20)
	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	@Column(name = "ACCOUNT_ID", length = 20)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "USER_NAME", length = 10)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "ROC_ID", length = 10)
	public String getRocId() {
		return this.rocId;
	}

	public void setRocId(String rocId) {
		this.rocId = rocId;
	}

	@Column(name = "ONSALE_PROMO_LIST_ID", length = 32)
	public String getOnsalePromoListId() {
		return this.onsalePromoListId;
	}

	public void setOnsalePromoListId(String onsalePromoListId) {
		this.onsalePromoListId = onsalePromoListId;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "IS_SEND_TO_LOYALTY", length = 1)
	public Character getIsSendToLoyalty() {
		return this.isSendToLoyalty;
	}

	public void setIsSendToLoyalty(Character isSendToLoyalty) {
		this.isSendToLoyalty = isSendToLoyalty;
	}

	@Column(name = "CO_DATE", length = 7)
	public Date getCoDate() {
		return this.coDate;
	}

	public void setCoDate(Date coDate) {
		this.coDate = coDate;
	}

	@Column(name = "LOYALTY_RESPONSE_XML", length = 4000)
	public String getLoyaltyResponseXml() {
		return this.loyaltyResponseXml;
	}

	public void setLoyaltyResponseXml(String loyaltyResponseXml) {
		this.loyaltyResponseXml = loyaltyResponseXml;
	}

	@Column(name = "INITIAL_ORDER_XML", length = 4000)
	public String getInitialOrderXml() {
		return this.initialOrderXml;
	}

	public void setInitialOrderXml(String initialOrderXml) {
		this.initialOrderXml = initialOrderXml;
	}

	@Column(name = "UPDATE_ESTORE_DATA_RESPONSE", length = 4000)
	public String getUpdateEstoreDataResponse() {
		return this.updateEstoreDataResponse;
	}

	public void setUpdateEstoreDataResponse(String updateEstoreDataResponse) {
		this.updateEstoreDataResponse = updateEstoreDataResponse;
	}

	@Column(name = "LY_CONFIRM_ORDER_REQUEST_XML", length = 4000)
	public String getLyConfirmOrderRequestXml() {
		return this.lyConfirmOrderRequestXml;
	}

	public void setLyConfirmOrderRequestXml(String lyConfirmOrderRequestXml) {
		this.lyConfirmOrderRequestXml = lyConfirmOrderRequestXml;
	}

	@Column(name = "LY_CONFIRM_ORDER_RESPONSE_XML", length = 4000)
	public String getLyConfirmOrderResponseXml() {
		return this.lyConfirmOrderResponseXml;
	}

	public void setLyConfirmOrderResponseXml(String lyConfirmOrderResponseXml) {
		this.lyConfirmOrderResponseXml = lyConfirmOrderResponseXml;
	}

	@Column(name = "COH_ORDER_ID", length = 32)
	public String getCohOrderId() {
		return this.cohOrderId;
	}

	public void setCohOrderId(String cohOrderId) {
		this.cohOrderId = cohOrderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UpgradePlusOrderId))
			return false;
		UpgradePlusOrderId castOther = (UpgradePlusOrderId) other;

		return ((this.getCono() == castOther.getCono()) || (this.getCono() != null && castOther.getCono() != null
				&& this.getCono().equals(castOther.getCono())))
				&& ((this.getTxid() == castOther.getTxid()) || (this.getTxid() != null && castOther.getTxid() != null
						&& this.getTxid().equals(castOther.getTxid())))
				&& ((this.getSubscriberId() == castOther.getSubscriberId())
						|| (this.getSubscriberId() != null && castOther.getSubscriberId() != null
								&& this.getSubscriberId().equals(castOther.getSubscriberId())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this.getAccountId() != null
						&& castOther.getAccountId() != null && this.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getRocId() == castOther.getRocId()) || (this.getRocId() != null
						&& castOther.getRocId() != null && this.getRocId().equals(castOther.getRocId())))
				&& ((this.getOnsalePromoListId() == castOther.getOnsalePromoListId())
						|| (this.getOnsalePromoListId() != null && castOther.getOnsalePromoListId() != null
								&& this.getOnsalePromoListId().equals(castOther.getOnsalePromoListId())))
				&& ((this.getMsisdn() == castOther.getMsisdn()) || (this.getMsisdn() != null
						&& castOther.getMsisdn() != null && this.getMsisdn().equals(castOther.getMsisdn())))
				&& ((this.getIsSendToLoyalty() == castOther.getIsSendToLoyalty())
						|| (this.getIsSendToLoyalty() != null && castOther.getIsSendToLoyalty() != null
								&& this.getIsSendToLoyalty().equals(castOther.getIsSendToLoyalty())))
				&& ((this.getCoDate() == castOther.getCoDate()) || (this.getCoDate() != null
						&& castOther.getCoDate() != null && this.getCoDate().equals(castOther.getCoDate())))
				&& ((this.getLoyaltyResponseXml() == castOther.getLoyaltyResponseXml())
						|| (this.getLoyaltyResponseXml() != null && castOther.getLoyaltyResponseXml() != null
								&& this.getLoyaltyResponseXml().equals(castOther.getLoyaltyResponseXml())))
				&& ((this.getInitialOrderXml() == castOther.getInitialOrderXml())
						|| (this.getInitialOrderXml() != null && castOther.getInitialOrderXml() != null
								&& this.getInitialOrderXml().equals(castOther.getInitialOrderXml())))
				&& ((this.getUpdateEstoreDataResponse() == castOther.getUpdateEstoreDataResponse())
						|| (this.getUpdateEstoreDataResponse() != null
								&& castOther.getUpdateEstoreDataResponse() != null
								&& this.getUpdateEstoreDataResponse().equals(castOther.getUpdateEstoreDataResponse())))
				&& ((this.getLyConfirmOrderRequestXml() == castOther.getLyConfirmOrderRequestXml())
						|| (this.getLyConfirmOrderRequestXml() != null
								&& castOther.getLyConfirmOrderRequestXml() != null
								&& this.getLyConfirmOrderRequestXml().equals(castOther.getLyConfirmOrderRequestXml())))
				&& ((this.getLyConfirmOrderResponseXml() == castOther.getLyConfirmOrderResponseXml())
						|| (this.getLyConfirmOrderResponseXml() != null
								&& castOther.getLyConfirmOrderResponseXml() != null
								&& this.getLyConfirmOrderResponseXml()
										.equals(castOther.getLyConfirmOrderResponseXml())))
				&& ((this.getCohOrderId() == castOther.getCohOrderId())
						|| (this.getCohOrderId() != null && castOther.getCohOrderId() != null
								&& this.getCohOrderId().equals(castOther.getCohOrderId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCono() == null ? 0 : this.getCono().hashCode());
		result = 37 * result + (getTxid() == null ? 0 : this.getTxid().hashCode());
		result = 37 * result + (getSubscriberId() == null ? 0 : this.getSubscriberId().hashCode());
		result = 37 * result + (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getRocId() == null ? 0 : this.getRocId().hashCode());
		result = 37 * result + (getOnsalePromoListId() == null ? 0 : this.getOnsalePromoListId().hashCode());
		result = 37 * result + (getMsisdn() == null ? 0 : this.getMsisdn().hashCode());
		result = 37 * result + (getIsSendToLoyalty() == null ? 0 : this.getIsSendToLoyalty().hashCode());
		result = 37 * result + (getCoDate() == null ? 0 : this.getCoDate().hashCode());
		result = 37 * result + (getLoyaltyResponseXml() == null ? 0 : this.getLoyaltyResponseXml().hashCode());
		result = 37 * result + (getInitialOrderXml() == null ? 0 : this.getInitialOrderXml().hashCode());
		result = 37 * result
				+ (getUpdateEstoreDataResponse() == null ? 0 : this.getUpdateEstoreDataResponse().hashCode());
		result = 37 * result
				+ (getLyConfirmOrderRequestXml() == null ? 0 : this.getLyConfirmOrderRequestXml().hashCode());
		result = 37 * result
				+ (getLyConfirmOrderResponseXml() == null ? 0 : this.getLyConfirmOrderResponseXml().hashCode());
		result = 37 * result + (getCohOrderId() == null ? 0 : this.getCohOrderId().hashCode());
		return result;
	}

}
